### ISSUE TITLE
Clarify whether 'filter' attribute is valid for <tspan> elements

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/svgwg#103]
There seems to be some confusion over whether you can apply a filter to a `<tspan>` element.

The spec states that 'filter' applies to "container elements (except mask) and graphics elements".  Technically `<tspan>` is in neither of those categories.

The Firefox folks have decided that it does not apply (see [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=917766)).

It partially works in Chrome, [but it is bugged](https://bugs.chromium.org/p/chromium/issues/detail?id=603157).

Filters on `<tspan>` elements work in IE.

It seems to me that it would be nice if they did work.  But either way, I think the filter effects spec should be updated to clarify this point.

**Comment by BigBadaboom** [comment]
fs@Opera just pointed out that the SVG2 spec has added the following paragraph (Section 10.3 The ‘text’ and ‘tspan’ elements)

> It is possible to apply a gradient, pattern, clipping path, mask or filter to text. When one of these facilities is applied to text and keyword 'objectBoundingBox' is used (see Object bounding box units) to specify a graphical effect relative to the "object bounding box", then the object bounding box units are computed relative to the entire ‘text’ element in all cases, even when different effects are applied to different ‘tspan’ elements within the same ‘text’ element.

I guess this issue is invalid since it appears this topic has already been discussed(?)  I didn't know.

**Comment by fsoder** [comment]
That - or a very similar - paragraph actually existed in the 1.1 spec too (10.4 I think, while 10.3 in SVG2 - or something like that).
It rhymes kind of poorly with https://www.w3.org/2016/01/14-svg-minutes.html#resolution01 though IMHO. And since you can do things like https://jsfiddle.net/tqdtw05x/ in HTML I'd expect the same to work in SVG (albeit the current Filter Effects draft is light on the unit resolution details...)

**Comment by AmeliaBR** [comment]
@BigBadaboom 

I can't find anything in the spec (SVG 2 or filters) that suggests a filter *shouldn't* apply to `<tspan>`.  The only complication is the definition of objectBoundingBox; as you've discovered, this is specced to be consistent with fill/stroke paint servers.  

If you have any suggestions for text that needs to be clarified, let us know.  Otherwise: do you want to follow up on those Chrome & Firefox bug reports, or should I?

**Comment by BigBadaboom** [comment]
I don't mind following up.  Before I do, is it out of the question that the specced bounding box behaviour could change?  As fsoder points out, it makes SVG inconsistent with HTML, and browsers aren't consistent nor unanimous on it.

**Comment by AmeliaBR** [comment]
I would like to, long-term, give authors an option to switch to a different bounding box, but that's not going to happen in SVG 2.  We definitely want objectBoundingBox behavior to be consistent between paint servers, filters, masks, etc.

**Comment by BigBadaboom** [comment]
I had already opened a bug against FF. It was marked a duplicate of the already-existing https://bugzilla.mozilla.org/show_bug.cgi?id=1062725

And what I thought was bugged behaviour in Blink is actually not. It follows the spec.

**Comment by fsoder** [comment]
https://drafts.fxtf.org/filters/#FilterProperty

> Applies to:	All elements. In SVG, it applies to container elements without the <defs> element and all graphics elements

Container elements(?): https://svgwg.org/svg2-draft/struct.html#TermContainerElement
Graphics elements(?): https://svgwg.org/svg2-draft/struct.html#TermGraphicsElement

Neither contains `<tspan>` ATM, but maybe the latter should contain it now that it's supposed to  implement SVGGraphicsElement?

I think that `'filter'` is not necessarily the primary issue here, but rather whether the paragraph at:
https://svgwg.org/svg2-draft/text.html#ObjectBoundingBoxUnitsTextObjects should remain given that SVGTSpanElement now implements getBBox, and (AFAICT) should return a box only covering the glyphs from the `<tspan>`.

**Comment by Tavmjong** [comment]
Waiting for Nikos http://www.w3.org/2016/05/26-svg-minutes.html#action01

**Comment by nikosandronikos** [comment]
A little further testing.
https://jsfiddle.net/dodgeyhack/sc7nhxwx/

For Chrome and Safari, the filter region is different for feGaussianBlur and feFlood.
feFlood appears to be using the entire text element region, while feGaussianBlur looks to be using only the area of the tspan.

**Comment by Tavmjong** [comment]
SVG 1.1 and SVG 2 text:

"It is possible to apply a gradient, pattern, clipping path, mask or filter to text. When one of these facilities is applied to text and keyword 'objectBoundingBox' is used (see Object bounding box units) to specify a graphical effect relative to the "object bounding box", then the object bounding box units are computed relative to the entire ‘text’ element in all cases, even when different effects are applied to different ‘tspan’ elements within the same ‘text’ element."

The Chrome behavior is correct. Both filters are being applied to the <tspan> element using the text element bounding box. The painting order is the text before the <tspan>, then the <tspan> then the text after the <tspan>. Since the 'red' <tspan> floods the entire text area it is covering the text before the tspan.

**Comment by Tavmjong** [comment]
Oops, the greater than/less than symbols got removed.

Should read:

The Chrome behavior is correct. Both filters are being applied to the tspan element using the text element bounding box. The painting order is the text before the tspan, then the tspan, then the text after the tspan. Since...

**Comment by nikosandronikos** [comment]
Yeah, I see what's happening. It's always the bounding box of the text element that's used for the filter area, but only the tspan text is input to the gaussian blur filter.
IE uses the bounding box of the tspan rather than the text element, but I haven't had a chance to test Edge yet.

**Comment by nikosandronikos** [comment]
I think for SVG 2 we don't need to do much, we have a category of element called 'text content elements' that includes **text**, **tspan**, and **textPath**.

I propose we modify the following text in [7.11 Object bounding box units](https://svgwg.org/svg2-draft/single-page.html#coords-ObjectBoundingBoxUnits):

> In the discussion that follows, the term applicable element is the element to which the given effect applies. For gradients and patterns, the applicable element is the graphics element which has its fill or stroke property referencing the given gradient or pattern. (For special rules concerning text elements, see the discussion of object bounding box units and text elements.) For clipping paths, masks and filters, the applicable element can be either a container element or a graphics element.

To:
In the discussion that follows, the term applicable element is the element to which the given effect applies. For gradients and patterns, the applicable element is the graphics element which has its fill or stroke property referencing the given gradient or pattern. For clipping paths, masks and filters, the applicable element is the element to which the clipping path, mask, or filter is applied. (For special rules concerning text elements, see the discussion of object bounding box units and text elements.)

Then we can update Filter Effects to enable filters on 'text content elements' as well as 'container elements' and 'graphics elements' once SVG 2 is out. We should probably change CSS Masking to apply clipping and masking to them as well.

**Comment by nikosandronikos** [comment]
If we do make this change in filter effects, we need to file a bug on IE to get them using the proper filter region.

We also need to file a bug on Chrome and WebKit for getBBox() on tspan - they are returning the bbox of the text element.

**Comment by AmeliaBR** [comment]
It looks like there are a couple FX specs, including CR specs such as blend modes, that reference SVG "container elements and graphics elements", so the fastest solution for us is to change SVG 2 so that it is clear that text content elements are graphics elements.  

Since these properties all applies to inline elements in CSS/HTML, there is no logical reason to prevent it on SVG text spans.  And since we've already resolved to make `tspan` and `textPath` transformable and with their own bounding boxes, the distinctions between a "graphics element" and a "text content" element have been pretty much eliminated.  We still have special rules for determining the bounding box for object bounding box units, but that's it.
