### ISSUE TITLE
Can we re-define attribute values to use ABNF or EBNF, not a mix of both?

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#108]
https://svgwg.org/svg2-draft/types.html#syntax

What are the differences between these notations?  Can we harmonize the few attributes that are defined using them to be consistent with one or the other?

Anyone who's familiar with these grammars, please self-assign!

**Comment by nikosandronikos** [comment]
We need to keep the reference to both.
ENBF is for path data. It's not used elsewhere.
ABNF is used for some externally defined values - e.g. lang.

I have done some minor tidy up to the text around EBNF and ABNF. I moved definitions of wsp and comma-wsp into the path grammar definition since it's unlikely we'll define anything else with EBNF in future.
