### ISSUE TITLE
Make "show" widget in element definitions boxes play nicely with screen readers

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#110]
In SVG2 spec element boxes, the "show" to expand categories is being read twice by JAWS/Firefox (and maybe others).

**Comment by dstorey** [comment]
I haven't tested it yet, but it may be because the "show" is included in generated content, which is read by screen readers. I don't see where it is included the second time though as there is no text node.

This would probably be better as a details/summary with polyfill as there is no aria in the current markup to show it is a complex control with expanded state, and there is no way to collapse it again after expanding it.
