### ISSUE TITLE
Rename the d attribute on textPath to 'path'

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#120]
https://www.w3.org/2016/04/21-svg-minutes.html#resolution02

**Comment by dirkschulze** [comment]
This probably should mean: add an alias?

**Comment by AmeliaBR** [comment]
@dirkschulze As far as I could test, no one has implemented it yet.  This was a new in SVG 2 feature (1.1 required an href to a separate path element) so there should be no breakage from changing it.

We want to use a different name from the `d` on a `<path>`, since the path in a `<textPath>` has quite a different effect and we want to be able to map them to different CSS properties.

**Comment by dirkschulze** [comment]
Ah right, currently we just reference paths.
