### ISSUE TITLE
Shouldn't gradientTransform precede object bounding box to user space conversion?

### ISSUE THREAD

**Issue by andrei-datcu** [w3c/svgwg#135]
According to:
https://svgwg.org/svg2-draft/pservers.html#RadialGradientElementGradientUnitsAttribute
> If gradientUnits="objectBoundingBox", the user coordinate system for attributes [...] is established using the bounding box of the element to which the gradient is applied (see Object bounding box units) and then applying the transform specified by attribute ‘gradientTransform’.

(As a side note, the above quote contains `fr` twice in the attribute enumeration. Should be `fy` instead.)

Shouldn't the `gradinentTransform` be the first one applied?
To quote from `graidentTransform`'s description:
>This additional transformation matrix is post-multiplied to (i.e., inserted to the right of) any previously defined transformations, including the implicit transformation necessary to convert from object bounding box units to user space.

**Comment by andrei-datcu** [comment]
@dirkschulze

**Comment by AmeliaBR** [comment]
I don't think there is a conflict, just the normal confusion that transformations can be described 2 ways: as a series of operations applied to the original shape to create the distorted shape (the first quote describes it this way), versus as a series of matrix multiplications.

That said, I think the entire paragraph (under `objectBoundingBox`) is rather confusing, because it implies that the final gradient is the result of transforming the individual points, rather than transforming the final rendered gradient.  I'm going to remove that sentence altogether, and therefore remove any ambiguity.

**Comment by Tavmjong** [comment]
'fr' type fixed. Thanks.
