### ISSUE TITLE
Define how to interpolate multiple paints in fill and stroke

### ISSUE THREAD

**Issue by karip** [w3c/svgwg#141]
A [`<paint>`](https://svgwg.org/svg2-draft/painting.html#SpecifyingPaint) value with multiple `<paint-layer>`s is a new type specified in the SVG2 spec. The spec should define how to interpolate it.

Perhaps it will be similar to the [proposed way](https://lists.w3.org/Archives/Public/www-svg/2013Apr/0040.html) to interpolate between svg gradients with cross-fade.

**Comment by AmeliaBR** [comment]
Cross-fade sounds like a good idea.  I think we want to move more & more towards uniting the concept of an SVG paint server with the concept of a CSS image data type.  

We still need to more clearly define how images as paint work, adapting all the CSS background image scaling & repeat properties to SVG, and defining how those same properties apply to SVG paint servers.  I'm personally hopeful that if we can clear up all those issues, we'll be able to approach CSS about allowing SVG paint server references anywhere CSS accepts an image type, so that meshes & hatches can be used as generic graphical effects, similar to filters and masks.

**Comment by tabatkins** [comment]
The CSSWG is already fine with SVG paint servers as CSS `<image>`; that's defined in the CSS Images spec.

**Comment by nikosandronikos** [comment]
Moving this issue into the larger issue #173
