### ISSUE TITLE
Percentages in 'letter-spacing' and 'word-spacing'

### ISSUE THREAD

**Issue by Tavmjong** [w3c/svgwg#143]
SVG 1.1 allows % on 'letter-spacing', 'word-spacing', and other properties that use `<length>`. SVG 2 moves % out of `<length>` and explicitly adds `<percent>` in the property definitions. This was not done for 'letter-spacing; and 'word-spacing'.

SVG 1.1 does not define what % is relative to for 'letter-spacing' and 'word-spacing'. Batik and rsvg use the diagonal of the viewport (but Batik's calculation is small by a bit). The more sensible reference would be font size.  None of the browsers seem to support % on these properties. 

We should either define what % is relative to or remove % as a valid value (the latter is effectively what is in SVG 2 at the moment).

**Comment by AmeliaBR** [comment]
The standard definition for both properties is in [CSS Text](https://drafts.csswg.org/css-text-3/#spacing).  They currently define percentages in word spacing as relative to the normal width of the word-separating space (this is new relative to [CSS 2.1](https://www.w3.org/TR/CSS21/text.html#propdef-word-spacing)).  Percentages are not valid in letter-spacing.

Where are you seeing text in SVG 2 defining allowed values for these properties?  The Editor's Draft points to CSS 3 as far as I can tell.

Since this _is_ a change from SVG 1.1, we should add a note somewhere explicitly warning about the backwards incompatibility.

**Comment by Tavmjong** [comment]
Note added. 9237e7288027fa94146f3d2e300021334abaa3fc
