### ISSUE TITLE
Shorter equivalent path for the <circle> element

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#153]
Currently, the spec defines an equivalent path for a `<circle>` element as follows:

> Mathematically, a ‘circle’ element is mapped to an equivalent ‘path’ element that consists of four elliptical arc segments, each covering a quarter of the circle. The path begins at the "3 o'clock" point on the radius and proceeds in a clock-wise direction (before any transformations). [Source](https://svgwg.org/svg2-draft/shapes.html#CircleElement)

I would change that definition to use just two elliptical arcs, starting from 12 o'clock.

```js
let cx = circle.cx.baseVal.value;
let cy = circle.cy.baseVal.value;
let r = circle.r.baseVal.value;

let equivalentPathData = [
  { type: "M",  values: [cx, cy-r] },
  { type: "A",  values: [r, r, 0, 0, 0, cx, cy+r] },
  { type: "A",  values: [r, r, 0, 0, 0, cx, cy-r] }
];
```

**Comment by BigBadaboom** [comment]
The starting position can't be changed because it will affect dash patterns.  Thus is not backwards comptable. Your path definition also travels in the opposite direction.

https://jsfiddle.net/mz98zL7x/

I don't know exactly the original reason that four segments were chosen rather than two, but I suspect it was for reasons of accuracy.  Arc segments are susceptible to numerical errors when the angle is large.

**Comment by jarek-foksa** [comment]
Thanks for explanation, the current definition makes sense to me now.

**Comment by jarek-foksa** [comment]
One more question - shouldn't the equivalent path end with "Z" segment?

**Comment by nikosandronikos** [comment]
Four segments gives a more useful result for marker-mid as well.
