### ISSUE TITLE
Update bounding box algorithm for wrapping text

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#159]
https://svgwg.org/svg2-draft/coords.html#issue15

**Comment by AmeliaBR** [comment]
Resolved (Amsterdam F2F, 20 June 2016) that the bounding box of text shouldn't be affected by inline size: use the bounding box based on the actual text layout.  _However_, for text in a shape, you should use the bounding box of the relevant shapes.  That way, paint servers and such can have predictable, controllable results for text in a shape.  If authors need that predictability, they can use text in a shape instead of inline-size.

So the issue is still open, just different.
