### ISSUE TITLE
<style> should be allowed everywhere where <script> is allowed

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#162]
`<script>` element is allowed as a child of almost every element, while `<style>` is allowed only inside `<defs>`, `<g>` and `<svg>`. I don't understand why those two conceptually similar elements should have different rules.

**Comment by AmeliaBR** [comment]
Sounds reasonable.  The HTML specs have also recently loosened up the rules on where a `<style>` is allowed, so I don't think we'd get any objections from browser implementers. (A `<syle>` element worked in all browsers previously anywhere in an HTML document, but it was technically invalid).  

@Tavmjong is somewhat horrified at the idea of having style elements at arbitrary locations, nested within shapes and such, but he's not 100% sure whether Inkscape would be able to keep track of them currently.   But since we're opening up the content model of basic shapes to include paint servers, markers, and other graphical effects elements, it makes sense to also allow a `style` containing, e.g., the animation rules for that content.

**Comment by jarek-foksa** [comment]
@AmeliaBR Yeah, having those elements in arbitrary locations is a real nightmare from the perspective of authoring tool authors. However, I don't see any technical reasons why Inkscape couldn't handle them.

**Comment by jarek-foksa** [comment]
I just tried putting `<style>` element inside `<rect>` and tested it on the latest version of Chrome, Safari and Firefox. It seems to work just fine everywhere.
