### ISSUE TITLE
<script> and <style> content model should allow only character data.

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#163]
Currently those elements can have any elements as children. I can't think of any scenario where this would be desirable or useful.

**Comment by AmeliaBR** [comment]
For title & desc, we need to keep the allowed child elements for backwards compatibility, although I was going to add a warning to authors that the extra markup has no impact on accessibility in modern browsers.  It was originally there with the idea that a plain-text browser could render properly marked up HTML descriptions instead of graphics.  It could still be useful if authoring tools are copying descriptions from other contexts which include formatted text.

**Comment by AmeliaBR** [comment]
But yes, I'm not sure what's the purpose of a free-for-all content model in `style` and `script`.  If anything, that's an implementation problem for the HTML parser, which presumably treats these as pure content data (instead of requiring an XML CDATA construct).

**Comment by jarek-foksa** [comment]
Related issue: https://github.com/w3c/svgwg/issues/102

**Comment by nikosandronikos** [comment]
Reference to some discussion:
https://www.w3.org/2016/06/21-svg-minutes.html#item06

**Comment by nikosandronikos** [comment]
The plan is that unless we hear some objections, we'll switch to match HTMLs content model for those elements.

**Comment by AmeliaBR** [comment]
[Current web browsers all support markup inside SVG script, unless you use XML CDATA notation, even with the HTML parser](http://jsbin.com/gihorozifa/1/edit?html,console,output).

**Comment by nikosandronikos** [comment]
Addressed in 7ab9cdf2b570e37cfc2e5a317de641d84a7c46bd
