### ISSUE TITLE
Make SVGAnimatedX data types extend DOMX data types wherever possible

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#175]
E.g., make  SVGAnimatedString a subclass of DOMString, that just happens to have (redundant, deprecated) getters named `animVal` and `baseVal` and a (redundant, deprecated) setter named `baseVal`.  (We've already removed any special meaning from `animVal`; it is no longer tied to SMIL animation.)

That way, things like SVGAElement.href and SVGElement.className would magically become compatible with HTMLAElement.href and HTMLElement.className for nearly all scripts that use them.

It works fine for JavaScript implementations (strings are objects, they can have properties, getters & setters), but I'm not sure if we're able to extend something like "DOMString" generically.

**Comment by BigBadaboom** [comment]
It will have ramifications for some API implementations. For example in Java, both are interfaces, and one interface can't inherit from another interface.  I wonder if this sort of change has happened before and how they resolved it.  One option (for the Java implementation) is to make SVGAnimatedString a 100% abstract class instead.

**Comment by dstorey** [comment]
@AmeliaBR to solve this for SVG href can't we do:

```
interface mixin SVGURIReference {
  [SameObject, PutForwards=baseVal] readonly attribute SVGAnimatedString href;
};
```
https://heycam.github.io/webidl/#PutForwards

Providing that works with the fancy xlink:href/href magic then getting/setting href should be the same as href.baseVal

**Comment by dstorey** [comment]
I overlooked something in the above. With setting href you could do the same as HTML: anchor.href = "foo"; (which puts forward to baseVal) but it wouldn't be the same for getting. You'd still get the SVGAnimatedString object of course. Maybe 50% better is still better though?

**Comment by dstorey** [comment]
I discussed this with @travisleithead and after much thought and whiteboard scribblings he came up with a similar approach to you. 

There are a few details to work out but we'd need to get something like [LegacyStringClass] defined in WebIDL (similar to[ LegacyArrayClass]) and use it on SVGAnimatedString (or a new replacement....I proposed SVGAnimatedSillyString). Then we'd need to make sure that setting the internal string representation also updated baseVal (and animVal) so that both getting/setting the string directly and href/className.baseVal both work. I think that was the gist of it.

**Comment by AmeliaBR** [comment]
Would this approach be extensible to SVGAnimatedBoolean/Integer/Number?

(And maybe also *Enumeration, which is currently spec'd as basic an SVGAnimatedShort, but without all the artistry and humour usually associated with an "animated short [film]".)

**Comment by dstorey** [comment]
They may need a different [LegacyFoo] but I've not looked into how they're used. If SVGAnimatedNumber returns a number instead of a string (just checked, it returns a float) then I guess it would. I'm not sure if they're as high a priority to fix though as they're not used on something that has direct equivalent in HTML are they? (it would be nice to fix them if it is easy but href is probably the most important thing to fix)

**Comment by AmeliaBR** [comment]
Agree that SVGAnimatedString, and the `<a>` element interfaces + `className` are the priorities.

The other SVGAnimatedX interface with X as a base type are only used a few times each. (See full [SVG DOM IDL](https://svgwg.org/svg2-draft/idl.html).)  And for all the SVG-specific interface properties, the plan (I think) is that [CSS Typed OM](https://drafts.css-houdini.org/css-typed-om/) will eventually make it possible to completely deprecate & replace them, so yeah, it's probably not worth a lot of logical maneuvers to make them more logical as-is.

**Comment by travisleithead** [comment]
Filed a WebIDL issue to help get some expert advice.

**Comment by longsonr** [comment]
I'm not getting any traction on DOMPoint/DOMRect etc because to use them in SVG I'd have to extend them (so they can be live). I suspect this kind of change would be equally unpalatable.

**Comment by dstorey** [comment]
#315 should be https://github.com/w3c/svgwg/pull/409 (we agreed to change target to DOMString due to low usage)

#312 is a HTML change and I'll work with them to do that (it is the same issue as moving the members into a shared mixin that would make the above change obsolete)

I'll do another PR to add putForwards/stringifier. I can also implement in Edge. PutForward generates all the code needed automatically so that is a trivial change. stringifier should be straightforward too. At least on baseVal. If we want to add on SVGAElement (probably in href's mixin) to match HTMLAElement.toString() behaviour of returning the href string, then that will need a custom specified stringifier. I believe you do that in WebIDL by specifying  new member stringifier and defining the behaviour in prose.

**Comment by AmeliaBR** [comment]
Closing this issue, in favour of a new issue for the chosen behavior: #546
