### ISSUE TITLE
Restore SVGSVGElement.prototype.getElementById

### ISSUE THREAD

**Issue by foolip** [w3c/svgwg#182]
It was removed in https://github.com/w3c/svgwg/commit/3d61d59f0d9e333c1afc5a548533c59cc5e58f7b

The Chromium issue and use counter:
https://bugs.chromium.org/p/chromium/issues/detail?id=313655 (when filed the DOM spec had it on `ParentNode`, now it's on `NonElementParentNode`)
https://www.chromestatus.com/metrics/feature/timeline/popularity/778

Usage is high enough that it doesn't seem worth inconveniencing anyone for this, given current support, see comments on the linked removal commit.

@annevk

**Comment by AmeliaBR** [comment]
To clarify:

This was removed from the SVGSVGElement interface because it was expected to be implemented on the general Element interface (but that didn't happen)?  I certainly see no harm in putting it back in.

Anyone have any details on whether any implementations have actually removed this feature yet?  Will we need to follow up with bug reports or is this just an editorial change?

**Comment by foolip** [comment]
That spec change was reverted in https://github.com/whatwg/dom/commit/f71d7de304e1ee25573279157dd6ce1c2aa2c4f2

The commit message links to https://www.w3.org/Bugs/Public/show_bug.cgi?id=23860 which is broken right now, but I'm pretty sure that it was a compat constraint, something like jQuery breaking.

I've just confirmed that Blink, Gecko, Edge and WebKit still all have `getElementById` on `SVGSVGElement`.

**Comment by nikosandronikos** [comment]
Element.getElementById() removal happened in 2013, yet the svgwg made a resolution in 2015 to remove SVGSVGElement.getElementById. So it sounds like it might not have just been removed because it was going to be defined elsewhere.
Unfortunately there was very little discussion at the time the resolution was made to remove it.
https://www.w3.org/2015/02/11-svg-minutes.html#item12
I think adding it back and maybe marking as deprecated in favour of document.getElementById would be a reasonable option, but I'll try to get some more feedback.

**Comment by foolip** [comment]
@erikdahlstrom, you're in the minutes, do you have any more context?

How is deprecation used in the SVG spec? This isn't something that I think should generate console warnings or be considered for later removal, so [deprecation in Blink](http://www.chromium.org/blink#TOC-Launch-Process:-Deprecation) wouldn't be appropriate.

**Comment by erikdahlstrom** [comment]
TBH I don't remember, but the usefulness of SVGSVGElement.getElementById is fairly limited IMHO. I think the WG was looking to remove old and under-used DOM APIs in general.

I'd still say a spec-level deprecation of SVGSVGElement.getElementById would be in order.

Regarding the work on the DOM spec, have the editors/WG given up entirely on scoped getElementById (under that or any other name)?

Sidenote: has anyone tested to see if SVGSVGElement.getElementById is actually implemented as being limited to the svg fragment in all browsers?

**Comment by annevk** [comment]
Since `getElementById` cannot be put on element, I don't think we'll add one. You can use `querySelector("#...")` instead and `query("#...")` at some point in the future.

**Comment by nikosandronikos** [comment]
@foolip Deprecation in the SVG spec is just an encouragement to use some alternative method.
The note says something like 'this feature may be removed in future and here's a better alternative that you should use'. Hopefully, if the encouragement works and usage drops enough the feature can actually be removed one day.

**Comment by foolip** [comment]
@erikdahlstrom, https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4289 is an ad-hoc test for the scoping, and Chrome, Edge, Firefox and Safari all show the same result:
```
log: document.getElementById("foo") => [object HTMLDivElement]
log: svg.getElementById("foo") => [object SVGGElement]
```

(So using `document.getElementById` does not always give the same result.)

Whether it's deprecated in the spec I'll leave to the WG members, but I want to say that even if [usage](https://www.chromestatus.com/metrics/feature/timeline/popularity/778) drops to zero I'm skeptical of ever removing, given that we are now in an interoperable state. Unlike, say, synx XHR, it's trivial to support and seemingly harmless.

**Comment by erikdahlstrom** [comment]
@foolip Re the test, from the SVG11 spec "Behavior is not defined if more than one element has this id". If that means 'in the document' or 'in this svg fragment' or something else is unclear though.

If the method is re-added to the spec, would you prefer to mandate the result you get in the testcase you made? Because that's not guaranteed by the old wording.

**Comment by annevk** [comment]
We should definitely define and mandate that behavior. Leave no thing undefined.

**Comment by nikosandronikos** [comment]
I'm going to reopen this issue.

I didn't give it enough consideration first time around and was a bit naive when considering possible alternatives.

I propose:
1. Rescind decision to deprecate this method. Because it will never be available on Element it is useful, more so than ever with inline SVG. There are potential alternative options, but they take some work by authors to achieve an exact result.
2. Define as in the DOM spec, where the first element, in document order, with the id is returned

**Comment by annevk** [comment]
Well, first element within the descendants.

**Comment by AmeliaBR** [comment]
One clarification: If the `<svg>` itself matches the `id`, does the method return it? Or is it strictly descendents only?  That's not an issue for "non-element parent node", but it is for SVGSVGElement.

**Comment by BigBadaboom** [comment]
Presumably it would be logical if it behaved the same as `querySelector("#foo")`, which would mean that it did not return itself.

https://jsfiddle.net/4neh8ogw/1/

**Comment by foolip** [comment]
Implementations only consider descendants, at least that's what I found with https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4296

**Comment by AmeliaBR** [comment]
@BigBadaboom @foolip Thanks for doing those tests.

The [SVG 1.1 function description](https://www.w3.org/TR/SVG11/struct.html#__svg__SVGSVGElement__getElementById) says "search this SVG document fragment", which I would read as including the `<svg>` as well, but if that's not how it is currently implemented, it makes sense to change it to be consistent with implementations and `querySelector`.

**Comment by foolip** [comment]
Using the phrasing from the DOM spec verbatim would be good, the implementation is shared anyway.

**Comment by nikosandronikos** [comment]
RESOLUTION: Restore SVGSVGElement.getElementById. Rescind previous resolution to deprecate. Spec just as it's specced in DOM - returns first descendant element in document order with the Id

https://www.w3.org/2016/07/07-svg-minutes.html#item01
