### ISSUE TITLE
Define all cases for intrinsic ratio

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#197]
Currently in the spec, we have this issue 
https://www.w3.org/TR/2015/WD-SVG2-20150915/coords.html#issue30

This section maybe isn't as well written as it could be, but I think it's complete in terms of describing all it needs to describe. But I would like a second opinion.

The constraints are:
- width and height are presentation attributes.
- the default value for width and height is `auto` and `auto` is defined to be 100%
- this means that width and height are never unspecified. The default is to be 100% of the containing block.
- If no viewBox exists, the extra transformation defined by the viewBox is simply omitted. Additionally ,preserveAspectRatio is ignored if no viewBox is given.

These constraints mean that the possible combinations are:

|width|height|viewbox|intrinsic ratio|
|-----|------|-------|---------------|
|length|length|VB.w x VB.h|width / height|
|length|percentage|VB.w x VB.h|VB.w / VB.h|
|percentage|length|VB.w x VB.h|VB.w / VB.h|
|percentage|percentage|VB.w x VB.h|VB.w / VB.h|
|length|length|unspecified|width / height|
|length|percentage|unspecified|undefined|
|percentage|length|unspecified|undefined|
|percentage|percentage|unspecified|undefined|

Which are all covered by the current prose.

So I'm tempted to just do some general tidy up of that section and close the issue. Does anyone who knows more about this than me disagree?

**Comment by AmeliaBR** [comment]
It looks like someone has done some re-writing since SVG 1.1, but this is an area that has been a historical problem for interoperability, so being extra clear is not a bad thing.

I agree with the red-text comments about changing the wording to be more consistent with CSS & the current spec.

The list of options skips over the case where _one_ of height or width is specified, but not the other.  This gets confusing when you get to the last paragraph, which seems to suggest that a used aspect ratio of 2:1 gets applied in that case.  Even CSS 2.1 as linked doesn't address the case where one dimension is specified by there is no intrinsic aspect ratio.  Which is perfectly possible in SVG.

We should update that link to point to [CSS 3 images](https://www.w3.org/TR/css3-images/#default-sizing), which addresses this case by applying the default sizes independently to width and height, rather than by applying a default 2:1 ratio.

Additional things to clarify: 

- `width` and `height` are presentation attributes, therefore the important value is the used value for each, regardless of whether it is set as an attribute or via CSS. 

- If an SVG View is in effect, the intrinsic aspect ratio can change: need to use the used value of `viewBox` assigned by the view.

- Just because an SVG doesn't have an `intrinsic` height & width, doesn't mean height and width are undefined.  E.g., in many rendering contexts, percentage height & width do have meaning.

**Comment by nikosandronikos** [comment]
Ok, I rewrote that section with reference to the default sizing algorithm in CSS 3 Images. Please have a look and let me know your thoughts.

**Comment by AmeliaBR** [comment]
Thoughts:

- Section title is a little verbose. Let's cut that down to "Intrinsic sizing properties of SVG content"

- I'd replace all references to width/height "presentation attributes" with "style properties".  Presentation attributes are one way of setting style properties; "used value" in particular is only defined in CSS terms.

- Did you intend to say that _all_ relative lengths are ignored for intrinsic sizing? That includes font-relative lengths such as `em` lengths.  I'd prefer to say something about using default font metrics to resolve such lengths to their px equivalents.

**Comment by nikosandronikos** [comment]
>  Section title is a little verbose. Let's cut that down to "Intrinsic sizing properties of SVG content"

Agree on the section title. Good suggestion.

>  I'd replace all references to width/height "presentation attributes" with "style properties". Presentation attributes are one way of setting style properties; "used value" in particular is only defined in CSS terms.

I went with sizing properties, since that's how they're referred to in the section where they're defined. https://svgwg.org/svg2-draft/geometry.html#Sizing.

> Did you intend to say that all relative lengths are ignored for intrinsic sizing? That includes font-relative lengths such as em lengths. I'd prefer to say something about using default font metrics to resolve such lengths to their px equivalents.

No, that was an oversight on my part. I've reworded it to exclude only auto and percentage values.
Do we need to say anything specific about font relative units? They're a `length` type so it's up to CSS to resolve them to something the same as they would for any other length.

Note: It turns out we also have a similar section in the SVG integration spec, but it's out of date.
https://svgwg.org/specs/integration/#svg-css-sizing

**Comment by AmeliaBR** [comment]
Looks great. I think that closes this issue. (Hooray!)
