### ISSUE TITLE
Reference W3C Web Animations

### ISSUE THREAD

**Issue by tobireif** [w3c/svgwg#22]
Should the list of options in
http://www.w3.org/TR/SVG2/animate.html#Introduction
include a link to W3C Web Animations?
http://www.w3.org/TR/web-animations-1/

**Comment by nikosandronikos** [comment]
I think it probably should.

**Comment by nikosandronikos** [comment]
Note that the list is now in a different spec:
 https://svgwg.org/specs/animations/

**Comment by tobireif** [comment]
@nikosandronikos 

> Note that the list is now in a different spec:
> https://svgwg.org/specs/animations/

No, the list is still at https://www.w3.org/TR/SVG2/animate.html#Introduction .

What you linked to is the "SVG Animations" spec (aka SVG SMIL Animation).

The list at https://www.w3.org/TR/SVG2/animate.html#Introduction lists SVG animation elements,  CSS Animations & Transitions, and JS-animation.

I hope they'll add W3C Web Animations (link https://www.w3.org/TR/web-animations/ ) to the list.

**Comment by nikosandronikos** [comment]
https://www.w3.org/TR/SVG2/ is the latest published working draft of the specification but because we're still editing SVG 2 it's not the most up to date copy.
The latest [editor's draft](https://svgwg.org/svg2-draft/) is what you should be looking at when suggesting changes for SVG 2.

The page you're linking to shouldn't actually exist.
The animation chapter has been removed from the SVG 2 spec. It has become the SVG Animations spec that I linked to. You'll see the [intro](https://svgwg.org/specs/animations/#intro) contains the list that you referenced in your issue. This spec includes SMIL, but it is not restricted to that.
For some reason the deleted chapter made it into the directory when the working draft was published - the fact it's showing as an 'editor's draft' and isn't listed in the contents gives hints to this.

**Comment by tobireif** [comment]
At
https://svgwg.org/svg2-draft/single-page.html#refs-InformativeReferences
there are these foot note ref targets:
"CSS3ANIMATIONS", "CSS3TRANSITIONS", neither of which is used/refd in the spec document.

I think I'd list all major W3C animation options, prominently in the spec, or none at all. I'd list and link to these:
CSS Transitions & Animation specs.
SVG Animation spec.
Web Animations spec.
JS-animation (requestAnimationFrame spec).

The list "SVG content can be animated in the following ways" should be more complete (eg as above), and it could be present in the SVG 2 spec, in the SVG Animation spec (where it is present now), or in both (that would be sensible as well).

**Comment by nikosandronikos** [comment]
I've added https://github.com/w3c/svgwg/issues/71. I'll tidy up the references before we publish CR.

**Comment by dirkschulze** [comment]
Closing this issue in favour of #71.

**Comment by tobireif** [comment]
The list at https://svgwg.org/svg2-draft/animate.html includes everything I listed (in https://github.com/w3c/svgwg/issues/22#issue-105236653 and in https://github.com/w3c/svgwg/issues/22#issuecomment-198372205 ), so it's OK to close this issue.

**Comment by dirkschulze** [comment]
@tobireif Thanks!
