### ISSUE TITLE
Remove support for "rev" attribute on <a> element

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#224]
This attribute has been deprecated in [HTML 5](https://html.spec.whatwg.org/multipage/obsolete.html#obsolete). It doesn't make sense to introduce it in SVG 2.

**Comment by AmeliaBR** [comment]
Hmm... this seems to be an area of disagreement between WHATWG and [W3C HTML specs](https://w3c.github.io/html/document-metadata.html#element-attrdef-a-rev).  Because it's additional semantic information with no required behavior from implementations, I'd lean towards including it.  But it's only there for consistency with HTML, so if the consistent thing to do is remove it, that's fine too.

Anyone have opinions and/or know the story behind the HTML disagreement?

**Comment by tabatkins** [comment]
It was intentionally removed from HTML5 (the last version) because it was a total failure in terms of usage, and Microformats usability studies showed that it was routinely misused.  It was added back to the new W3C HTML without discussion, and over severe (after-the-fact) objections from Tantek.

Overall best practice is to, when necessary, introduce reverse-valued relations, rather than try and use `rev`, because people simply can't reliably work the `rev` semantics.  We should not be trying to reintroduce it in SVG2.

**Comment by AmeliaBR** [comment]
Resolved at the [18 August 2016 telcon](https://www.w3.org/2016/08/18-svg-minutes.html#resolution01):

> RESOLUTION: Remove rev attribute from SVG 2

@nikosandronikos, can you make the edits and then close the issue?
