### ISSUE TITLE
Adjust stroke/fill to be compatible with proposed Fill & Stroke spec

### ISSUE THREAD

**Issue by fantasai** [w3c/svgwg#230]
We had resolved to have stroke/fill be shorthand properties that reset all of the stroke-* or fill-* properties. The SVG2 spec should reflect this, as it is a breaking change (and not a “new feature” that can be deferred).

For stroke there were two possibilities discussed: shorthanding just the paint properties (i.e. not dashing or widths), or shorthanding all stroke-* properties. The latter might be preferable, but compat is a question here.

(This should probably be Agenda+ for TPAC.)

**Comment by AmeliaBR** [comment]
Who/when was this resolved? If `stroke` and `fill` became a reset for any of the SVG 1.1 properties, that would be a huge breaking change, messing up all sorts of content; I would never accept that.  

The plan was to make stroke and fill shorthands for the new CSS-background-inspired sizing longhands.  But since those were deferred to the proposed new fill & stroke spec, the only change for SVG 2 was to allow lists of multiple paint layers.

**Comment by AmeliaBR** [comment]
Based on discussion at the 4 August 2016 telcon, we concluded:

- `stroke` and `fill` cannot become shorthands for any of the existing properties, as this would be unacceptable for web compat

- However, `stroke` and `fill` can be expanded as shorthands for *new* properties to control CSS image types as paint sources, as proposed in the new [CSS Fill and Stroke draft spec](https://drafts.fxtf.org/paint/).  E.g., `stroke-image` and `stroke-color` will both be reset by `stroke`.

- There *may* also be additional new shorthands introduced, such as `stroke-dash` as a shorthand to set dasharray and dashoffset and the proposed other dashing options.

- In order to give @tabatkins & @fantasai flexibility while developing that spec, and in order to ensure that SVG implementations for layered paint can be updated at the same time as for CSS images, **SVG 2 will *not* have layered paint.**

- SVG 2 will still have `context-fill` and `context-stroke` keywords; these reset the entire fill/stroke shorthand and will be added to the new CSS spec.

- SVG 2 will still have `child` references to paint sources, as an alternative to `url()` references; these will be added to the new spec as an option for individual image values.

**Comment by AmeliaBR** [comment]
Assigning this to @nikosandronikos because he [took an action](https://www.w3.org/2016/08/04-svg-minutes.html#action02) to make the edits to remove multi-layer paint from SVG 2.
