### ISSUE TITLE
SVG Image size conflicts with size property and CSS style

### ISSUE THREAD

**Issue by shanmuga-m** [w3c/svgwg#237]
Spec links:
https://svgwg.org/svg2-draft/embedded.html#Placement
https://svgwg.org/svg2-draft/geometry.html#Sizing

 As per the links, for svg element , the initial value is set to '0' for the attribute (the former
link) while it is 'auto' for the properties.

but for SVG Image(the second link), The value auto for width and height on the ‘image’ element is calculated from the referenced image's intrinsic dimensions and aspect ratio, according to the CSS default sizing algorithm.

In that case, If SVG Image  intrinsic size explicitly not specified like below, 

    <image xlink:href="400x400.png" />

Since width and height are presentation attributes, should it render with 400X400 based on second link or 0x0 based on first link ?

Thanks!!

**Comment by AmeliaBR** [comment]
Thanks for catching this @shanmuga-m 

In SVG 1.1, there was no `auto` and the initial value (if the attribute wasn't specified) was 0.  The `auto` sizing option was added to SVG 2 relatively recently, but I guess we didn't catch all the necessary editorial changes.  

The initial value for `width` and `height` is always `auto` (that's defined in CSS), although for some aspects of SVG (but _not_ images) we treat `auto` as 0.

That entire section in the [Embedded Content chapter](https://svgwg.org/svg2-draft/embedded.html#Placement) should be re-written to make it clear that these are the geometry properties / presentation attributes being used, not separate attributes.

**Comment by AmeliaBR** [comment]
Taking a closer look at the Embedded content chapter, it looks like we have two different legacies of the pre-geometric properties draft.  For `image` and `foreignObject`, there is the outdated attributes box.  For the HTML namespace elements, there's a warning that the only way to position them is with transforms, and then special rules for computing width & height in a pseudo-box-model context.  

I would expect that you could use x/y/width/height geometric properties to position and size all of these elements in a consistent manner, even if the presentation attributes are only available on the elements in the SVG namespace.  I think that also avoids any confusion on how width & height should be interpretted for the HTML elements.

I'm tidying up the chapter with that in mind, but I wanted to give folks (particularly @nikosandronikos and @tabatkins) a heads up, since this is slightly more than an editorial change.

**Comment by nikosandronikos** [comment]
Sounds good. Your suggestion is consistent with my expectations of where we were going in SVG 2.
