### ISSUE TITLE
Documentation should mention SMIL polyfill

### ISSUE THREAD

**Issue by Emasoft** [w3c/svgwg#24]
Eric Willigers from Google has created an official SMIL polyfill implemented entirely on the Web Animations API. You can find it here: https://github.com/ericwilligers/svg-animation
This would allow the playback of SMIL animations EVERYWHERE, even in browsers that until now didn't supported SMIL (like old IE browsers).

**Comment by erikdahlstrom** [comment]
I'm not sure that specs should recommend any particular polyfill, instead they should describe the requirements for handling the given language IMHO.

Aside, some technical things to consider:
* Is it a true polyfill, as in, does it work in browsers that don't support the Web Animations API?
* Will it conflict with or incur heavy additional downloads in browsers that already support SMIL?
* Does it perform well on mobile devices, wrt loading, interactivity and framerate?

Also note, a js polyfill like this won't work inside <img> elements since scripting is disabled there. For this polyfill to work in that context it'd require some policy changes on the UA side.
