### ISSUE TITLE
UTF-16 code points for addressable characters

### ISSUE THREAD

**Issue by r12a** [w3c/svgwg#259]
11.1.1. Definitions
https://svgwg.org/svg2-draft/text.html#Definitions

> addressable character
>     A character that is addressable by text positioning attributes and SVG DOM text methods. Characters discarded during layout such as collapsed white space characters are not addressable, neither are characters within an element with a value of none for the display property. Characters are **addressed by their index measured in UTF-16 code units**, prior to applying any text-transform conversions, as described for the methods in the SVGTextContentElement interface; **as a result, a single Unicode character may map to multiple addressable characters**. 

We hope that it will not be possible to address a single surrogate character, and think that this should be stated in the definition.

We also suggest "a single Unicode code point may map to" to clarify the meaning better.

We would actually prefer that accessible characters be defined in terms of Unicode code points, rather than UTF-16 code units. 

Addison proposes the following alternative text for "Characters are addressed..."

> The address of a given Unicode character (codepoint) is measured in UTF-16 code units, prior to applying any text-transform conversions, as described for the methods in the SVGTextContentElement interface; as a result, a single Unicode code point may be represented by multiple UTF-16 code units.

Finally, a quick example of what it means to address a character means would probably help readers understand the purpose of an addressable character. We struggled with that.

**Comment by AmeliaBR** [comment]
Thanks for this and the other comments.

I think we all agree that it would be preferable if characters were defined in terms of Unicode code points, not UTF-16 code units, but that is a now a backwards-compatibility issue.  A future spec may introduce some sort of global switch to turn on proper Unicode mode.

The other clarifications can probably be made, but @Tavmjong knows this chapter better than I do.

**Comment by Tavmjong** [comment]
Unicode points would be better. Hmm, I wonder if anyone actually uses UTF-16 to map characters to text attributes. SVG1.1 uses UTF-16 due to its use in DOM2, see https://www.w3.org/TR/SVG/text.html#InterfaceSVGTextContentElement
It appears DOM4 allows both UTF-8 and UTF-16 (https://www.w3.org/TR/WebIDL-1/#idl-DOMString) in some cases.

**Comment by nikosandronikos** [comment]
Discussed during [today's telcon](https://www.w3.org/2016/09/15-svg-minutes.html#item04).

Regarding characters being treated as UTF-16 code points, we agree this isn't the best behaviour, but we're constrained by backwards compatibility issues. I've filed #280 as a future wish list item.

@Tavmjong will check whether there's any other little editing tasks raised by this issue.

**Comment by aphillips** [comment]
(discussed by I18N WG at TPAC)

Please see our comment on #280 

Please note that the terms "Unicode code point" (a single Unicode character) and "UTF-16/UTF-8 code unit" (a single encoding unit in a character encoding; in UTF-16 this is 16-bits, in UTF-8 this is a byte) can be confusing.

**Comment by AmeliaBR** [comment]
See #537, where it was discovered that most browsers use different counting methods for the attributes (based on code points / Unicode characters) vs DOM methods (based on UTF-16 blocks / JS string indexing). We [resolved](https://github.com/w3c/svgwg/issues/537#issuecomment-416351148) to match that behavior in the spec, since it is a more useful behavior.

So this whole definition will need to be rewritten or dropped completely.

**Comment by dirkschulze** [comment]
Closing in favour of 
https://github.com/w3c/svgwg/issues/537
