### ISSUE TITLE
Opacity properties should affect nothing but opacity

### ISSUE THREAD

**Issue by tobireif** [w3c/svgwg#264]
In some cases (in eg SVG 1 or 2 or CSS), setting/changing opacity changes the stacking order / changes which items overlap which. That is very surprising for the user of your technology / the SVG/web developer, and it is very inconvenient because it can require time and effort to work around the issue.

Please make sure that the presence or absence of any opacity values never affect anything except opacity.

**Comment by nikosandronikos** [comment]
SVG 2 now supports the [z-index](https://svgwg.org/svg2-draft/render.html#ZIndexProperty) property from CSS. As with CSS, using this in conjunction with opacity can affect the rendering order. If an author does not explicitly set z-order to something other than the default, then opacity has no effect on the rendering order. So this is not a breaking change, and is not something that will confuse authors that don't use z-index.

The requirement to group together objects into layers that can be rendered once on the GPU and then re-used is for performance reasons, and is important. If a different behaviour was needed, then we would use a different property name for depth ordering (e.g. not z-index, because then the behaviour would be different to CSS). But I don't think the extra knowledge required to use z-index is that onerous.

**Comment by tobireif** [comment]
While I was working on http://codepen.io/TobiReif/pen/ZpERON , at some point I came across the issue - I set opacity (from CSS IIRC) and one or more items were suddenly overlapped by others. That is very bad SVG-user experience design. (Not sure why the issue appeared in an SVG using SVG1, perhaps the browser had jumped ahead to SVG2 in this aspect.)

Regarding CSS:

See https://github.com/w3c/csswg-drafts/issues/464 .

It is not sensible to spec the same issue in SVG 2, because it would not be SVG-user friendly. It would cause the same problems and confusion caused by the behaviour of CSS. People even use "opacity:0.99" hacks ... https://philipwalton.com/articles/what-no-one-told-you-about-z-index/

> is not something that will confuse authors that don't use z-index.
...
> I don't think the extra knowledge required to use z-index is that onerous.

It is! The user of your spec would use "z-index" to change the stacking order, and would use opacity properties to change the opacity - requiring the user of your spec to know that setting/changing "opacity" affects anything other than opacity is (frankly speaking) bad API design. The user might simply (while setting/changing nothing but opacity values) get bitten by the issue, without knowing the cause(!)

I've been using z-index (in CSS) for many years, and until recently I never knew about the very surprising and very problematic fact that opacity properties can change stacking order.

Please make sure that the presence or absence of any opacity values never affects anything except opacity. No matter any z-index values.

Please re-open this issue ticket, please reconsider, and please convince the SVG WG.

The normal opacity properties should affect nothing but opacity. You then could consider offering additional options/properties eg because of performance considerations.

**Comment by tobireif** [comment]
Or, if you have to perpetuate the (sorry for the word) mess from CSS (because of compatibility) , you could offer an additional property, eg "opacity-without-side-effects" (it would affect nothing but opacity, no matter z-index, tspans, groups, 3D transforms, blend modes, etc). A new property will be better known (it would be listed by MDN, in books, etc) than some arcane implementation-related spec details.

**Comment by tabatkins** [comment]
> While I was working on http://codepen.io/TobiReif/pen/ZpERON , at some point I came across the issue - I set opacity (from CSS IIRC) and one or more items were suddenly overlapped by others. That is very bad SVG-user experience design. (Not sure why the issue appeared in an SVG using SVG1, perhaps the browser had jumped ahead to SVG2 in this aspect.)

As Nikos said, as long as you're relying solely on the default z-index (which SVG1 does, by definition), nothing ever changes order when you apply opacity/filter/etc.  That said, Chrome/Webkit does have a compositing bug (which we've had for a long time, because it's very hard/expensive to fix properly, tho we're finally getting to the point where we should be able to do it) where "composited" things (things which get put onto a separate GPU layer, due to things like opacity/filters/etc) can jump into the wrong visual layer. That's probably what you're hitting; it's got nothing to do with the spec at all.

That said, even in SVG2, what you're asking for is *actually impossible* (at least, not without a lot of fakery behind the scenes).  The 'opacity' property, along with all the other visual effects like 'filter' and such, are "group" properties - they apply to their entire subtree as a group, as if the subtree was painted into a canvas and then the visual effect was applied.  This is fundamentally incompatible with other items getting sandwiched inbetween elements of the group.  In some cases you can fake it - split the group in half and do the work on each half separately - but in the general (and relatively common) case, you can't; you'd get a noticeably different display from the splitting than you'd have without it.  CSS's situation isn't a mess, it's the logical consequence of mixing "group" properties with layer reordering.

**Comment by tobireif** [comment]
I think I'll be able to handle the issue in some way when the re-ordering happens.

But I hope you will be able to improve SVG (SVG2) by making sure that your users won't be surprised by the side effects, and won't have to read the spec just for setting opacity without changing the stacking order, and won't be tempted to use the published hackish workaround(s).

A user of eg SVG2 who is (eg using z-index and) setting/changing opacity shouldn't have to worry about the various possible reasons why the *opacity* property could affect *stacking order*. (Ditto for any other properties which have side-effects.)

If you can't fix the existing property by ensuring it is side-effect free, please consider offering a new property that is side-effect free. (If necessary make it independent of "grouping" etc. Anything that's necessary to make it 100% side-effect free.) Setting/changing that property would be guaranteed to affect opacity and nothing else. It would do what its name says and would not cause problems by doing more than it says it does.

(And yes, it would also be great if the Chrome and WebKit bugs could get fixed, but as you say that's not in scope for a spec ticket.)

**Comment by tabatkins** [comment]
Once again, a "side-effect free" group operation is impossible without cheating.  Here's an example:

```
<svg>
 <g style="opacity: .5;">
  <rect x="0" y="0" width="100" height="100" fill="red" />
  <rect x="50" y="50" width="100" height="100" fill="yellow" />
 </g>
</svg>
```

As you can see, by putting `opacity` on the `<g>`, the red and yellow rectangles go transparent *as a group* - the yellow still fully occludes the red where they overlap, because they're effectively drawn at normal opacity, then made transparent as a group.

Now, imagine sandwiching another rect between the yellow and red, filling *some* of the overlap area but not *all* of it. What would the effect be?  Would the new rectangle be visible thru the yellow, even tho the red is fully occluded?  What if the new rectangle was made transparent as well? Would it show the red behind it, even tho the yellow fully occludes the red?

None of these options make sense, or can even be implemented without behind-the-scenes hackery.  The only way to get something that *can* be sandwiched between red and yellow is to make the red and yellow rectangles *individually* transparent, like:

```
<svg>
 <recta x="25" y="25" width="100" height="100" fill="black" />
 <g>
  <rect x="0" y="0" width="100" height="100" fill="red" style="opacity: .5;" />
  <rect x="50" y="50" width="100" height="100" fill="yellow" style="opacity: .5;" />
 </g>
</svg>
```

Now you can sandwich a rectangle between the two and get a simple, consistent, understandable display.  However, the yellow no longer occludes the red square.  This might be the effect you want, or it might not.  (This sort of effect going badly is sometimes seen in early 3D video games creating a "ghost" or "vision" by making a character model partially transparent. The eyes and teeth/mouth are often separate "objects" to the game, so they go transparent separately, leading to a frightening "evil skull" effect where you can see their whole eyeball and jaw thru their ghost-skin. More modern games properly transparent-ify the whole character model together, avoiding this effect.)

This trade-off, between group effects and individual effects, is *inherent*. You can't get around it thru engineering, tho in some cases you can manually hack things to work (using clipping masks to manually implement occluding, for example).  There is no way for SVG to offer a "side-effect free" version of opacity, or any filter-like effect.

**Comment by tobireif** [comment]
Thanks for the explanation!

**Comment by tobireif** [comment]
Tab explained to me in a reply to an email that opacity etc are 100% side-effect free when they're applied to elements that don't have children. (even if there is z-index etc)

Structuring an SVG accordingly is a non-hackish solution for achieving side-effect free opacity, thus the whole issue is resolved enough for me.

(Regarding the Chrome bug - is there a bug report page?)

**Comment by tobireif** [comment]
This is an example (linked from https://philipwalton.com/articles/what-no-one-told-you-about-z-index/ ) where changing opacity for one item (an item without any children elements / not a group) changes stacking order:

http://codepen.io/philipwalton/pen/dfCtb

In that example there's z-index (as SVG might soon have), and there's "opacity: .99" for the red item. I can set "opacity: 0.5" and the red item becomes more faint, and stays behind the two other items. When I set "opacity: 1.0", that red item moves to the foreground - it suddenly overlaps the other items.

That probably will confuse SVG users who do use z-index. Is it not possible (in the spec) to ensure that when someone uses z-index and changes only the opacity value, the stacking order stays the same? In that example (linked above) the red item should always stay where it is / changing opacity should not change the stacking order. I don't see, in such cases where no group-opacity is involved, it would be impossible to ensure that changing opacity is completely side-effect free. Document order and z-index would affect nothing but stacking order (overlaps), and opacity would affect nothing but opacity (except when there's group-opacity as Tab had explained).

**Comment by tobireif** [comment]
(My goal is not to annoy you (the SVG WG), but instead to see whether the many users of SVG can be spared some annoyance by making the "API" less surprising/problematic.)

**Comment by nikosandronikos** [comment]
> This is an example (linked from https://philipwalton.com/articles/what-no-one-told-you-about-z-index/ ) where changing opacity for one item (an item without any children elements / not a group) changes stacking order:

That's not true, the example does use groups. The opacity is changed on the div element, which is a grouping element. The z-index is applied to the object within the group.

The example is contrived to make a point. It's useful for explaining the finer points of stacking contexts, but It's not a good way to structure a document. But having thought about the structure of this document. I do have an idea of how we might be able to reduce any possible confusion - though it sacrifices flexibility.

There are legitimate reasons to want to change the opacity of a group, and change the position in the z axis of one element in the group - the group might be used to apply a common transformation perhaps (note transform doesn't create a stacking context in SVG). But in this case, you just can't do it all with one group and that's not going to change. A group can only represent the set of objects that are transformed, or the set of objects that are adjacent in the z axis.

This leads me to how we can reduce confusion. This may be achieved by forcing the group to only represent the set of objects that are adjacent in the z-axis. We can define SVG to make the parent object of any element that has a z-index other than 'auto' form a stacking context. This would mean that the use of z-index inside a group can only be used to control the stacking order within that group. It's restrictive, but mostly consistent with how groups should be used.

This might be a terrible idea (it's pretty late here), or we may not want to be that restrictive. But I'll reopen this for comment.

**Comment by nikosandronikos** [comment]
It would also be nice to have some explicit way to force a stacking context without something like opacity:0.99 or transform:rotate(0)

**Comment by karip** [comment]
I wouldn't change SVG to behave differently from HTML. Stacking contexts, z-index, opacity, transform, they all are shared and I hope they are treated the same way in both languages.

A stacking context can be explicitly created with "[isolation: isolate](https://drafts.fxtf.org/compositing-1/#isolation)". However, I'm not sure why it has a special case for SVG.

**Comment by nikosandronikos** [comment]
@karip There are already some differences. `transform` for example doesn't create a stacking context in SVG.

**Comment by tobireif** [comment]
> That's not true, the example does use groups. The opacity is changed on the div element,
 > which is a grouping element. The z-index is applied to the object within the group.

Oops, you're right! A mistake on my part. I hadn't looked properly it seems and thought that opacity was applied to the span. Sorry.

It then works beautifully, as Tab had explained to me:
"opacity etc are 100% side-effect free when they're applied to elements that don't have children. (even if there is z-index etc)"

In http://codepen.io/philipwalton/pen/dfCtb , when I change the first rule from
```
div:first-child {
  opacity: .99; 
}
```
to
```
.red {
}
```
:
The red item is behind the other items (following the document order), then brought to the foreground using "z-index: 1". Then when I (in the first rule) set ```opacity: 1```, nothing changes (as expected), and when I change the opacity value to "0.5", the opacity of that red items gets changed as intended - without a side-effect changing the stacking/overlaps. Beautiful.

Not sure what could be done regarding the potentially confusing results in the other cases (while staying backwards-/CSS-compatible). Regarding your above idea for reducing confusion - probably best to discuss it directly with the SVG WG and CSS WG.

Thanks all!

**Comment by AmeliaBR** [comment]
Not to cause a diversion, but @tabatkins comment re `transform` is incorrect.

The `transform` attribute and `transform` property are supposed to be equivalent in their impact.  The only difference is that the attribute allows the legacy syntax re units and commas.  This is also why Chrome's implementation of transform-origin (relative to the shape instead of the coordinate system) was such a problem.

**Comment by tabatkins** [comment]
Hey hey hey, that was *Nikos'* comment. ^_^  But my point is still valid - due to the default origin, and the limited set of possible transforms, you can't tell whether the `transform` attribute affects stacking order just from examining the effect of transforms.

**Comment by trusktr** [comment]
> As you can see, by putting opacity on the <g>, the red and yellow rectangles go transparent as a group - the yellow still fully occludes the red where they overlap, because they're effectively drawn at normal opacity, then made transparent as a group.

This makes sense in certain cases, especially 2D ones.

> (This sort of effect going badly is sometimes seen in early 3D video games creating a "ghost" or "vision" by making a character model partially transparent. The eyes and teeth/mouth are often separate "objects" to the game, so they go transparent separately, leading to a frightening "evil skull" effect where you can see their whole eyeball and jaw thru their ghost-skin. More modern games properly transparent-ify the whole character model together, avoiding this effect.)

I'd rather have this than nothing at all (or rather than flattening, because flattening is honestly worse than the teeth-behind-the-jaw problem), and, in reality, if someone were transparent, you *would* see their teeth and eyeballs, so that is valid. 

The latest css-transforms spec removes this feature, which is a bad idea. The spec should instead *add* the flattening feature and leave the existing feature in tact (while speccing it).

**Comment by trusktr** [comment]
Also, the solution isn't to simply apply opacity to the leaf nodes, because in reality non-leaf nodes are also rendered.

f.e. the following is a hypothetical 3D scene where each item is placed and rotated (using `matrix3d`) relative to it's parent (for convenience, rather than calculating world transforms manually from a virtual tree):

```js
<style>
    ...
    div {
        transform-style: preserve-3d;
    }
    ...
</style>

...
<div style="transform: matrix3d(...)">
    this is content

    <div style="transform: matrix3d(...)">
        this is content

        <div style="transform: matrix3d(...)">
            this is content
        </div>
    </div>
</div>
...
```

You, and people in the public-fx thread, propose that in order to make everything transparent we should apply opacity to the elements directly.

1. that is impossible in the above example without changing the markup, otherwise the whole object will be flattened as soon as the parent-most div has opacity applied to it.
2. the opacities will be inherited and multiplied anyways according to new spec.
3. someone who has no access to the HTML and can only modify the CSS is out of luck, because this requires a markup change.
4. After making the markup change (using the non-nested approach for CSS3D), the opacities will no longer be multiplied which will require JavaScript in order to do the multiplication.

This is no good.

**Comment by trusktr** [comment]
Also, the solution isn't to simply apply opacity to the leaf nodes, because in reality non-leaf nodes are also rendered.

f.e. the following is a hypothetical 3D scene where each item is placed and rotated (using `matrix3d`) relative to it's parent (for convenience, rather than calculating world transforms manually from a virtual tree):

```js
<style>
    ...
    div {
        transform-style: preserve-3d;
    }
    ...
</style>

...
<div style="transform: matrix3d(...)">
    this is rendered content

    <div style="transform: matrix3d(...)">
        this is rendered content

        <div style="transform: matrix3d(...)">
            this is rendered content
        </div>
    </div>
</div>
...
```

You, and people in the public-fx thread, propose that in order to make everything transparent we should apply opacity to the elements directly.

1. That is impossible in the above example without changing the markup, otherwise the whole object will be flattened as soon as the parent-most div has opacity applied to it.
2. The opacities will be inherited and multiplied anyways according to new spec.
3. Someone who has _no access to the HTML and can only modify the CSS_ is out of luck, because this requires a markup change.
4. After making the markup change (using the non-nested approach for CSS3D), the opacities will no longer be multiplied which will require JavaScript in order to do the multiplication.
5. Changing the markup changes the structural meaning that is being conveyed, and possibly changes the semantical meaning of the content as far as spiders and crawlers are concerned.
6. Library authors like me, who depend on (and prefer) the nested approach of defining 3D scenes using `preserve-3d`, and who are defining custom elements that can contain content just like the `rendered content` in the above examples, will now have to render to a separate root element where all the 3D objects are non-nested, all transforms are multiplied manually rather than the HTML/CSS engine, and all opacities are multiplied manually rather than the HTML/CSS engine.
7. Users of libraries made by those authors will not be able to place content into the custom elements in a reliable way. It destroys CSS selection because either the original content remains behind in the custom elements and content is cloned into the new non-nested scene, or the content is moved by the library and placed into the new non-nested scene, and either way is bad.

This is not good.

**Comment by trusktr** [comment]
Flattening makes no sense for anyone using `preserve-3d` and whom wants to apply opacity to nested object (_without having to painstakingly modify the markup_).

**Comment by progers** [comment]
@trusktr, are you making a different argument here than on the public-fx thread? If not, can we try to keep that discussion on public-fx?

**Comment by trusktr** [comment]
Same argument, but maybe it doesn't matter here because SVG is 2D, and the behavior makes sense to me (everything in SVG is flat already, and there are no 3D transforms).

Since we're in this thread, I'd like to point out that 3D scenes (of the preserve-3d kind) in HTML are not 2D like SVG, and shouldn't be treated as such.
