### ISSUE TITLE
Add comment to SVGSVGElement IDL that deselectAll() is deprecated

### ISSUE THREAD

**Issue by SebastianZ** [w3c/svgwg#268]
The [description for the `SVGSVGElement.deselectAll()` method](https://svgwg.org/svg2-draft/struct.html#__svg__SVGSVGElement__deselectAll) says that the method is deprecated.

This should be reflected in the [IDL definiton for `SVGSVGElement`](https://svgwg.org/svg2-draft/struct.html#InterfaceSVGSVGElement) like it's done for other deprecated methods like `forceRedraw()`.

Sebastian

**Comment by nikosandronikos** [comment]
The indication for `forceRedraw()` and a few other methods is because those methods have no effect but are kept in the interface so as to not break things.

`deselectAll()` is not in that category.

It might be worth grouping all deprecated methods within their IDL definitions, but that would be a global change greater than the scope of this issue.
