### ISSUE TITLE
Consider adding a switch to control how Addresssable Characters are treated

### ISSUE THREAD

**Issue by nikosandronikos** [w3c/svgwg#280]
[Addressable characters](https://svgwg.org/svg2-draft/text.html#TermAddressableCharacter) are indexed by their UTF-16 code points due to backwards compatibility reasons.

It would be nice to have a switch to index by UTF-8 code points - either a global switch or one on each of the various methods of the SVG text interfaces.

It would also be good to be able to map to typographic characters / grapheme clusters? Is this feasible?

**Comment by fsoder** [comment]
If adding a 'switch', wouldn't it be better served as a switch to use code points as the "addressing unit". After all that's something that likely needs to be tracked regardless or which internal format (encoding) is used. That would open up a path out of the whole "code units addressing" issue.

**Comment by AmeliaBR** [comment]
I agree with @fsoder.  Switching to UTF-8 blocks isn't an improvement over UTF-16 blocks.  It just means that even more logical characters would get split over multiple "addressable characters".

We want to be able to count actual Unicode code points, regardless of how many bytes it takes to represent them.  This is consistent with the new EcmaScript 6 [`codePointAt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt) and [`fromCodePoint`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint) String methods.  (These replace the `charCodeAt` and `fromCharCode` methods which relied exclusively on UTF-16 surrogate pairs.)  Unfortunately, the EcmaScript Unicode conversion doesn't seem to yet support any easy way of finding the number of distinct code points in a string or substring.  Even the position argument used by `codePointAt` still seems to be based on the UTF-16 indexing.

**Comment by aphillips** [comment]
(discussed by I18N WG at TPAC)

The problem here is one of terminology. A "Unicode code point" is what SVG is defining as a "character": a single Unicode value. Counting code points is ideal, since a character cannot be split. 

However, since SVG is based on DOMString, which itself is defined in terms of UTF-16, probably UTF-16 code units are a necessary part of SVG's implementation. A health warning should be included to ensure that Unicode code points (characters) are not split in half.

UTF-8 code units (i.e. bytes) suffer from the same "addressable character" issue as UTF-16, as a character can take 1, 2, 3, or 4 bytes per character to encode.

**Comment by boggydigital** [comment]
Not blocking updated 2.0 CR publication - assigning 2.1 WD milestone

**Comment by AmeliaBR** [comment]
Closing this as redundant based on the testing and resolution in #537

**Comment by AmeliaBR** [comment]
(If someone wants to propose a set of new _DOM methods_ that use proper codepoints, that can be a separate issue.)
