### ISSUE TITLE
Create a wiki page listing deferred SVG 2 features

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#284]
There were a number of features that had been planned for SVG 2 but were deferred to future modules, because they were holding up any chance of getting to CR this year.

It would be nice to have a summary wiki page listing these, and any resolutions about them, with links to the draft modules.

**Comment by boggydigital** [comment]
We'll be tracking changes since 1.1 (additions, deprecations and changes) in SVG 2.0 specification itself: https://svgwg.org/svg2-draft/changes.html and very likely won't have group capacity to this the proposed list of changes outside the specification. 

This is not blocking updated 2.0 CR publication - closing this issue
