### ISSUE TITLE
Contradiction in spec in regards to SVGUseElement.instanceRoot etc

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/svgwg#330]
Appendix [L.2.5. Document Structure chapter]() states:

> Removed the SVGElementInstance and SVGElementInstanceList interfaces, and the corresponding attributes on the SVGUseElement interface.

However `SVGElementInstance` and the attributes of `SVGUseElement` are actually still there.  Perhaps due to Shadow DOM rewrite (?)

- [5.14.12. Interface SVGElementInstance](https://svgwg.org/svg2-draft/single-page.html#struct-InterfaceSVGElementInstance)
- [5.14.10. Interface SVGUseElement](https://svgwg.org/svg2-draft/single-page.html#struct-InterfaceSVGUseElement).

**Comment by AmeliaBR** [comment]
The [SVG 2 Changes appendix](https://www.w3.org/TR/SVG2/changes.html) is more of a log describing the editing process than a net result.  There are other cases where changes have been made and then re-verted or obsoleted by other changes.  During the different working draft versions of the spec, the changes for the latest working draft were always highlighted.

Later on [in that list](https://www.w3.org/TR/SVG2/changes.html#structure), you'll see

> Properties formerly defined on the SVGElementInstance object are now defined as a mixin interface extending SVGElement

As you guessed, this was part of the Shadow DOM re-write, trying to re-introduce a bit of backwards compatibility while still moving forward.

If you have a concern about the final spec, please file a separate issue.  I'm closing this one as I don't think this is a major inconsistency. (Although I recognize that it means that the Changes appendix is not as useful as it could otherwise be.)
