### ISSUE TITLE
Shouldn't getCharNumAtPosition take an argument of type DOMPointReadOnly rather than DOMPoint

### ISSUE THREAD

**Issue by longsonr** [w3c/svgwg#389]
https://www.w3.org/TR/SVG2/text.html#InterfaceSVGTextContentElement

Shouldn't  getCharNumAtPosition take an argument of type DOMPointReadOnly rather than DOMPoint

Compare with https://www.w3.org/TR/SVG2/struct.html#InterfaceSVGSVGElement where the IntersectionList methods take DOMRectReadOnly arguments.

**Comment by AmeliaBR** [comment]
Why would the input parameter need to be restricted to read only, in either case? You're calculating a result based on the current point value, not creating a permanent relationship to the object.

If anything, the intersection list functions are the ones that should change. I don't know why the parameters are specified as read only, but I wouldn't be surprised to discover it's because of some overzealous find & replace when the read only interfaces were defined.

**Comment by longsonr** [comment]
The input parameter is not restricted to read only. DOMPoint inherits from DOMPointReadOnly. If the input is DOMPointReadOnly you can pass either type. What you're saying is that calling this method won't change the values of the passed in object.

**Comment by tabatkins** [comment]
So, yes, it should indeed be switched to ReadOnly.

**Comment by AmeliaBR** [comment]
> If the input is DOMPointReadOnly you can pass either type. What you're saying is that calling this method won't change the values of the passed in object.

Ah, I see. The naming scheme doesn't make it clear that the mutable versions are a subclass of the read only versions, not the reverse&mdash;although that of course makes sense when it comes to the exposed interface: `X` is all the features of `XReadOnly`, plus mutability.

So yes, this is an obvious error, then. Otherwise we'd be breaking compatibility with SVG 1.

Still, it's technically a substantial change, so we should get a resolution on the next telcon.

@longsonr Have you reviewed similar interfaces to see if the same error crops up anywhere else?

**Comment by longsonr** [comment]
I checked DOMPoint/DOMPointReadOnly and DOMMatrix/DOMMatrixReadOnly. I think that's it. I didn't find anything else.

**Comment by progers** [comment]
Do `SVGGeometryInterface`'s `isPointInFill` and `isPointInStroke` have the same issue?
https://svgwg.org/svg2-draft/single-page.html#types-InterfaceSVGGeometryElement

These are currently defined as:
```
interface SVGGeometryElement : SVGGraphicsElement {
  ...
  boolean isPointInFill(DOMPoint point);
  boolean isPointInStroke(DOMPoint point);
  ...
}
```

**Comment by tabatkins** [comment]
Yes.

**Comment by longsonr** [comment]
Ahh, when I looked through the APIs, I actually only looked though the ones Firefox currently implements, so I may have missed some things. Firefox does not implement isPointInFill or isPointInStroke currently.

**Comment by longsonr** [comment]
What should SVGPointList look like?

**Comment by AmeliaBR** [comment]
> What should SVGPointList look like?

Good question. None of the "XXXList" methods actually modify the contents of the objects in the list, so the content objects can be read only, even when the list is modifiable. All the methods in [the `SVGPointList` interface](https://svgwg.org/svg2-draft/single-page.html#shapes-InterfaceSVGPointList) should probably accept the read-only versions.

That said, there's text in there about how a point list can be read-only even if the individual point objects are read-write, so I'm not sure whether there was a clear compatibility reason for that decision.  Maybe @dirkschulze knows?

**Comment by fsoder** [comment]
SVGPointList is a list of mutable points, so using DOMPoint there seems appropriate - that the list methods themselves does not mutate the objects does change what is stored in the list. Methods could (and maybe should?) take `DOMPoint or DOMPointReadOnly` and then invoke the same copying semantics as read-only DOMPoints are subjected too. The objects returned would still be DOMPoint regardless (since they represent a mutable entry in the list.)

As for "read-only DOMPoint" (I'm not finding the text about read-only list with read-write items - that sounds odd) I suspect that stems from `animatedPoints`, which has since been turned into an alias of `points` probably making the point about read-only points moot.

**Comment by AmeliaBR** [comment]
> (I'm not finding the text about read-only list with read-write items - that sounds odd)

It's in the prose for the SVGPointList interface:

> A DOMPoint object can be designated as read only, which means that attempts to modify the object will result in an exception being thrown. When assigning to a read only DOMPoint's x, y, w or z IDL attribute, a NoModificationAllowedError must be thrown instead of updating the internal coordinate value.

> Note that this applies only to the read-write DOMPoint interface; the DOMPointReadOnly interface, which is not used for reflecting the ‘points’ attribute, will already throw an exception if an attempt is made to modify it.

I'm not quite sure what the intent of those paragraphs is.

**Comment by fsoder** [comment]
That only talks about read-only DOMPoints - not SVGPointList. The whole "read-only object" thing is there because of the various `animVal`s (and similar, like `animatedPoints`) which were supposed to be read-only, but that couldn't be expressed through IDL in all cases (for instance SVGNumber works fine to just mark `readonly` in IDL, but SVGLength doesn't. Having SVGLengthReadOnly et.c would've done the trick though.) Presumably this is remnants from when `baseVal === animVal` was not always the case, and thus it can probably be removed.

**Comment by domenic** [comment]
A bit late I guess, but input parameters should always take DOMPointInit. Both DOMPoint and DOMPointReadOnly are too restrictive. We fixed a few canvas methods in a similar way recently in HTML.

**Comment by dirkschulze** [comment]
I really like the proposal from @domenic to use `DOMPointInit` instead of `DOMPointReadOnly` (and I think it is less confusing as well).

One could bring up the argument that it might be easier for implementations to comply to `DOMPointReadOnly` than to the `DOMPointInit` usage. Because of the mapping of `SVGPoint` implementations don't really need to do much. However, `SVGPoint` maps to `DOMPoint` and not `DOMPointReadOnly`. So changing `DOMPoint` to `DOMPointReadOnly` already requires changes to implementations.

I would propose to go either one of the following 2 paths:
1. If we are concerned that implementations are not updating their implementations to `DOMPointInit` in time to get SVG2 to REC, we shouldn't do any change to the current interfaces for level 2 at all (not even use `DOMPointReadOnly`) and update the spec in an errata or another revision when we see implementations adapt.
2. Go with `DOMPointInit` for level 2 already.

I'd prefer 2 but maybe we should get implementers buy in first.

**Comment by tabatkins** [comment]
> One could bring up the argument that it might be easier for implementations to comply to DOMPointReadOnly than to the DOMPointInit usage.

??? DOMPointInit is just a dictionary; you just check that the passed object, whatever it is, has x/y properties.  Dictionary-handling is already pretty automatic in impls; I think it gets handled automatically by your binding-generator code.

**Comment by dirkschulze** [comment]
```js
text.getCharNumAtPosition({x: 50, y: 15});
```

Firefox:
> TypeError: Argument 1 of SVGTextContentElement.getCharNumAtPosition does not implement interface SVGPoint.

Safari:
> TypeError: Argument 1 ('point') to SVGTextContentElement.getCharNumAtPosition must be an instance of SVGPoint

Chrome:
> Uncaught TypeError: Failed to execute 'getCharNumAtPosition' on 'SVGTextContentElement': parameter 1 is not of type 'SVGPoint'.

**Comment by dirkschulze** [comment]
@tabatkins Misunderstood your comment. So we are in agreement then: `DOMPointReadOnly` and `DOMPointInit` require work on the implementers side. With the resolution to use `DOMPointReadOnly` we could and should go with `DOMPointInit` directly.

As stated, the alternative is no change at all which should work with todays implementers code in theory but is not preferable.

**Comment by BigBadaboom** [comment]
>I really like the proposal from @domenic to use DOMPointInit instead of DOMPointReadOnly (and I think it is less confusing as well).

But `getCharNumAtPosition()` is an existing function in 1.1.  Switching to `DOMPointReadOnly` would not break backwards compatibility.  But `DOMPointInit` is, isn't it?

**Comment by dirkschulze** [comment]
@BigBadaboom No. Rather the opposite. Beside `DOMPoint` (`SVGPoint`), `DOMPointReadOnly` you can also provide a dictionary.

**Comment by tabatkins** [comment]
Right. Using DOMPointReadOnly (an interface) requires that the passed object be either a DOMPointReadOnly or a subclass. Using DOMPointInit (a dictionary) just requires that the object have the dictionary's properties; in this case, `x` and `y`.

**Comment by BigBadaboom** [comment]
> just requires that the object have the dictionary's properties

Is that defined somewhere?  I couldn't find anything in the WebIDL spec.

Or do you mean that they are functionally equivalent in JS?  How does that affect DOM implementations in other languages?

**Comment by tabatkins** [comment]
> Is that defined somewhere? I couldn't find anything in the WebIDL spec.

That's literally the definition of what it means for a function to take a dictionary type, specified in <https://heycam.github.io/webidl/#es-dictionary>.

> How does that affect DOM implementations in other languages?

WebIDL intentionally only defines a mapping to/from JS.  Other languages can do whatever they want.

**Comment by BigBadaboom** [comment]
@tabatkins Okay thanks. I was going by https://www.w3.org/TR/WebIDL-1/  I wasn't aware of theat github repo.

**Comment by tabatkins** [comment]
Always check the Editors Drafts (linked from the header information on the spec), especially when the official draft is years out of date, as in this case. ^_^

**Comment by dstorey** [comment]
re @zcorpan's comment in #326 this should be optional. 
@dirkschulze should we reopen this or make a new bug?

**Comment by longsonr** [comment]
What would happen if the argument was omitted? Is omitting the argument and getting whatever is defined as the default ever going to be useful?

**Comment by dirkschulze** [comment]
@dstorey I'll post a follow-up patch.

@longsonr Without arguments it falls back to `{x: 0, y: 0, z: 0, w: 1}` - the default values of `DOMPointInit`. This might not be particular useful but is a small price for the flexibility win of the function IMO. Do you disagree?

**Comment by longsonr** [comment]
The flexibility is an overall win.
