### ISSUE TITLE
SVG 1.1 Errata: How to Proceed?

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#390]
A valid errata for SVG 1.1 was reported on the mailing list: https://lists.w3.org/Archives/Public/www-svg/2018Mar/0003.html

Although our focus is SVG 2, SVG 1.1 still remains the existing SVG recommendation. Do we have a process for making corrections to SVG 1.1 2nd Edition?  There is an [errata page for the spec](https://www.w3.org/2011/08/REC-SVG11-20110816-errata), with only one entry. Does anyone know where it is defined?

**Comment by boggydigital** [comment]
Not blocking updated 2.0 CR publication - assigning 2.0 Recommendation milestone to clean this up before 2.0 REC.

With that said I understand that this is 1.1 - we should revisit this after 2.0 publication, which is likely 2.1

**Comment by svgeesus** [comment]
The link in the original report has rotted due to a) /TR/SVG now redirects to /TR/SVG2 and b) the section with the error was moved to the rendering chapter.

* [correct SVG 1.1 link](https://www.w3.org/TR/SVG11/painting.html#VisibilityControl)
* [correct SVG2 link](https://svgwg.org/svg2-draft/render.html#VisibilityControl)

The error has been corrected in SVG2, which says 

> Note that display is not an inherited property. 

Given that SVG2 was already updated, it seems clear there is SVGWG consensus on the correctness of the errata report. 

I updated the [SVG 1.1 errata](https://www.w3.org/2011/08/REC-SVG11-20110816-errata).
