### ISSUE TITLE
Suggest dropping requirement for text-align-all and text-space-collapse

### ISSUE THREAD

**Issue by ewilligers** [w3c/svgwg#486]
All the [required properties](https://svgwg.org/svg2-draft/styling.html#RequiredProperties) are supported by two or more browsers, except for text-align-all and text-space-collapse, which are not supported by any browsers.

[text-align-all](https://drafts.csswg.org/css-text/#text-align-all-property)
"This longhand of the text-align shorthand property ..."
"Authors should use the text-align shorthand instead of this property."
All browsers support text-align and it is already in the list of required properties.

[text-space-collapse](https://drafts.csswg.org/css-text-4/#propdef-text-space-collapse)
[Can I use](https://caniuse.com/#search=text-space-collapse): "This CSS property (formerly known as white-space-collapse or white-space-collapsing) is not supported in any modern browser, nor are there any known plans to support it."

The full list of required properties not supported by browsers:

**Blink**: 4

- font-variant-position (supported by Firefox and WebKit)
- glyph-orientation-vertical (supported by Edge and WebKit)
- text-align-all
- text-space-collapse

**Firefox**: 6

- alignment-baseline (supported by Blink and Edge and WebKit)
- baseline-shift (supported by Blink and Edge and WebKit)
- color-rendering (supported by Blink and WebKit)
- glyph-orientation-vertical (supported by Edge and WebKit)
- text-align-all
- text-space-collapse

**WebKit**: 9

- font-size-adjust
- font-variant
- text-align-all
- text-align-last
- text-decoration-color
- text-decoration-line
- text-decoration-style
- text-orientation
- text-space-collapse

**Edge**: 21

- color-interpolation
- color-rendering
- font-kerning
- font-variant-caps
- font-variant-east-asian
- font-variant-ligatures
- font-variant-numeric
- font-variant-position
- image-rendering
- isolation
- paint-order
- shape-rendering
- text-align-all
- text-decoration-color
- text-decoration-line
- text-decoration-style
- text-orientation
- text-rendering
- text-space-collapse
- transform-box
- vector-effect

**Comment by ewilligers** [comment]
We could also consider dropping the requirement for [glyph-orientation-vertical](https://www.w3.org/TR/css-writing-modes-3/#glyph-orientation).

CSS Writing Modes 3 describes it as Obsolete. "While supporting this property is optional, UAs that do so must alias glyph-orientation-vertical as a shorthand of text-orientation"

We already require text-orientation.

**Comment by Tavmjong** [comment]
I believe Adobe generated content using 'glyph-orientation-vertical' which is why it was kept. We (Inkscape) do not support it but do support 'text-orientation'. 

We also do not support 'text-align-all' or 'text-space-collapse'.

We support all the other properties listed above with the exceptions of ''color-rendering' (we do support 'color-interpolation-filters'), shape-rendering', 'font-variant' shorthand (we support in master all the longhand properties as well as the CSS 2.1 'font-variant' property), 'text-align-last', and 'transform-box'.

**Comment by AmeliaBR** [comment]
I'm fine with deferring to CSS Writing Modes for `glyph-orientation-vertical`, although I hope UAs won't rush to remove support, since there is legacy content using it.

For other properties without implementations, we could either drop them from the list or word it as "UAs must support this property for SVG content if they support it for other CSS-styled content".  (Quite frankly, I'd like to add a few more properties to the list with that condition, like `text-shadow` and `text-transform`, both of which we didn't want to require universally because they aren't supported in non-browsers.)

**Comment by ewilligers** [comment]
BTW, the CSS Writing Modes spec for glyph-orientation-vertical says '90' should be supported, but Edge and Safari do not support '90'. Instead they support more angles with units e.g. '180deg' and '270deg' (and 'auto' '0deg' '0' '90deg').

**Comment by svgeesus** [comment]
@ewilligers does your PR https://github.com/w3c/svgwg/pull/490 satisfy this issue, or are more edits needed?

**Comment by ewilligers** [comment]
No additional edits needed.
