### ISSUE TITLE
Directly referencing the HTML Sequential focus navigation and tabindex

### ISSUE THREAD

**Issue by richschwer** [w3c/svgwg#50]
I think we all agree that having a common place to reference tabindex and sequential focus navigation is a good thing I have serious concerns over just pointing to the existing HTML specification. When I put the sequential focus navigation components in SVG2 HTML5 was still in flux and they were trying to lock it down. There are a number of significant differences between HTML5 and SVG that make this problematic. Here are just a few:

- Form elements are all focusable and more of these were added in HTML5. These effect tabbed focus navigation and none of them exist in SVG. In fact, I see the current SVG spec. pointing to the HTML 5.1 focus model and it does not even have all the elements that would appear in the tab order. For Example, where is details/summary? IOW the HTML 51 spec we are referring to is not even complete. 

- SVG2 is XML based and many attributes are in the DOM. For example, _title_ and _desc_. These can have the tabindex attribute as the group resolved earlier to have all elements support tabindex. These are not mentioned in the HTML51 spec. and how to handle them. Are these element inert? The HTML5 editing module does not say as it was designed for HTML.

- The focus model pointed to by SVG2 (the current version) refers to a _body_ tag that does not even exist in SVG2. This is the text: _target node is a Document that has a body element._

- SVG2 also has its own DOM interfaces that are not are not equivalent to HTML even though, when I modified them they now include the related .tabindex feature. 

- The document we now refer to discusses _contenteditable_ as it is part of an editing section. None of that applies to SVG2. 

- Section 5.4.2 of the HTML Focus model spec. refers to _img_. We don't have an _img_ tag. We have an _image_ tag. 

So, this puts us in a difficult position. We can't just point to it as it is not testable (per the spec.). What should really be done is that both groups create a single module that deals with focus navigation across the two documents that is inclusive of SVG and frankly is also accurate in terms of HTML 5.1. In fact, HTML5 has moved toward a modular design that would accommodate that. I believe this will take much longer than we have for the current SVG2 schedule. I believe what we have puts SVG at risk unless the group's intent is to just ignore the spec. and test it the way we think it should work. 

I see only two options:
1. Delay both specs. and build a common focus navigation module that works for both specifications.
2. Go back to what we had and work on a number of common modules in SVG2.x that better harmonizes SVG2 and HTML.next after we release.

**Comment by tabatkins** [comment]
`<title>` and `<desc>` don't generate boxes in the tree, so they don't participate in focus navigation.

**Comment by richschwer** [comment]
I understand but there is nothing in the HTML spec. that says that:
https://www.w3.org/TR/html51/editing.html#the-tabindex-attribute
This is what we are pointing to, currently, in the SVG spec. 

My point being is that the HTML spec., currently, does not accommodate SVG to the extent it needs to. It may in the WhatWG version but it does not here.

**Comment by AmeliaBR** [comment]
Building on the HTML spec is important, but there needs to be clear guidance about which elements can be made focusable with `tabindex` or should already be focusable by default. The HTML spec mostly defers to "platform conventions" which aren't useful (in many cases, platform conventions for SVG are currently not to have good keyboard support!).

I've put together a draft section for review by the WG to review, as part of [Pull request #55](https://github.com/w3c/svgwg/pull/55). See that link for details on changes.  I'd like to discuss it at the next telcon.

It's not integrated into that pull request yet, but Rich also mentioned to me concern about referencing the HTML 5.1 spec instead of HTML 5. 

HTML 5.1 introduces modal dialogs, which add a lot of extra complication to focus management, and the relevant spec changes may not yet be stable (I don't know the status of browser implementations).  Since this complication isn't relevant to SVG, it may be preferable to link to the stable (& simpler) HTML 5 spec.

**Comment by AmeliaBR** [comment]
Closed by the merged changes.

Note that I didn't switch the HTML links to HTML 5.0, as some of the linked terms I was using weren't in the older spec and it would have required a more thorough re-write.  We'll need to keep an eye out for dead links as HTML gets edited.
