### ISSUE TITLE
Defer z-index due to lack of implementations

### ISSUE THREAD

**Issue by EdorianDark** [w3c/svgwg#553]
Since sadly the z-axis is not supported #489 and #483 it should be removed from render:

https://github.com/w3c/svgwg/blob/7157a830278f314fb048e762a780321dbe809233/master/render.html#L374

**Comment by AmeliaBR** [comment]
There is still a conceptual z-axis for layout, even if we (sadly) cannot control it with `z-index`.

It might be possible to remove the entire section on stacking contexts, but we'd need to do it very carefully, since SVG still needs to work within a larger CSS framework that uses that concept.

And of course, we still hope to re-introduce `z-index` for SVG if we can get implementer commitments, so it may be helpful to hold onto the stacking context definitions for that.

@ewilligers You pushed the edits removing `z-index`, what were your thoughts about the larger stacking context section?

**Comment by dirkschulze** [comment]
@AmeliaBR I’d prefer this to be done in a new modular spec. If we are not actively supporting this feature in SVG2 then we should move it out. Maybe we should create a more general SVG CG as incubator. So far we just have the SVG font CG.

**Comment by ewilligers** [comment]
I only suggested removing the `z-index` property text as support had not been implemented. I think it is might be the highest priority feature to add post-publication (motivated by Accessibility), it simply needs implementation.

**Comment by dirkschulze** [comment]
Closing the issue. `z-index` is no longer part of the spec and the notation of z axis is still required.
