### ISSUE TITLE
Move dataset & other shared IDL attributes from SVGElement to HTMLOrSVGElement

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/svgwg#60]
The current draft of the SVG spec defines `dataset` attribute on the [SVGElement](https://svgwg.org/svg2-draft/single-page.html#types-InterfaceSVGElement) interface while HTML 5 spec defines it on the [HTMLElement](https://html.spec.whatwg.org/multipage/dom.html#elements-in-the-dom) interface.

Is there any particular reason why `dataset` couldn't be defined just once on the `Element` interface like other similar attributes such as `classList`?

**Comment by AmeliaBR** [comment]
I don't think `dataset` can be generalized to all XML languages (because of the expectations it creates re valid attributes), so putting it on `Element` is unlikely to happen.  

However, it may be preferable to define it within the DOM specs as a "mixin" interface that can then be implemented by both `HTMLElement` and `SVGElement`.  That would ensure that we had one, canonical definition that would always be updated consistently.

Anyone want to take responsibility for looking into this possibility with HTML WG and WHATWG?

**Comment by dstorey** [comment]
There is now a PR for this and blur/focus/tabindex in HTML https://github.com/whatwg/html/pull/3543

**Comment by dstorey** [comment]
To be clear, we're moving this to a mixin in HTML (tests pending) that will still be included on SVGElement, rather than moving it to Element.

**Comment by annevk** [comment]
In the above referenced commit I said that it fixed this issue, but I guess what still remains is that you need to remove `dataset` from SVGElement's IDL.

**Comment by AmeliaBR** [comment]
Yep, marking this as "needs edits" and updating the title to match the chosen solution.

**Comment by AmeliaBR** [comment]
This brings up again the issue of whether SVG wants to link normatively to WHATWG interfaces; we currently reference W3C versions.  With the new WHATWG royalty commitments, it's probably less of an issue, but still a little messy & political to make the change.

I'll file an issue on W3C/html to ask if they can mirror the change, but not sure how long that might take.

**Comment by domenic** [comment]
We would appreciate it if in working collaboratively with us, you did not then turn around and request that another group copy our work so that you can proceed to ignore our work in your spec :(.
