### ISSUE TITLE
member-svg-media-type@w3.org is no longer active

### ISSUE THREAD

**Issue by maxnordlund** [w3c/svgwg#655]
I found a typo (#654) and tried to email this list as it is written at the bottom of the page i question (https://www.w3.org/TR/SVG/mimereg.html).

But it got bounced with the message that the mailing list is no longer active. So I email site-comments@w3c.org and they directed me here.

I'm not totally sure what makes the most sense, but any email address mentioned in a spec should probably be reachable, even if it redirects to site-comments or similar.

**Comment by svgeesus** [comment]
Thanks for reporting this!

Yes, the contact point for comments should certainly be reachable (and there is no reason that t be W3C Member-only).

I note that IANA [links directly back to the W3C registration](https://www.iana.org/assignments/media-types/media-types.xhtml#image) so it seems we can fix this by editing at our end, without troubling IANA.

**Comment by maxnordlund** [comment]
Great to hear :)

**Comment by svgeesus** [comment]
By the way

> **Person & email address to contact for further information**:
>    Chris Lilley, Doug Schepers (member-svg-media-type@w3.org).

is odd because no-one needs to contact anyone, the specificatin is freely available. I guess tht isn't always the case, particularly for registrations in the `vnd.` subtrees.

But it is good to fix the link in any case. 

For completeness, I looked at the (W3C Member only) archive for the [email address in the the registration](https://lists.w3.org/Archives/Member/member-svg-media-type/). There is no archive, which means no-one ever tried to mail that address while the address was active.

**Comment by maxnordlund** [comment]
Lol, well it's nice to be the first I guess.

**Comment by svgeesus** [comment]
You are welcome! (also late for me, good night!)
