### ISSUE TITLE
Support transform-origin as a presentation attribute

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svgwg#688]
Based on a [question from a colleague](https://mobile.twitter.com/Mamboleoo/status/1126040958045491200), I discovered that 3 of 4 major browsers (Chromium, WebKit, and EdgeHTML) currently support `transform-origin` as a presentation attribute. EdgeHTML requires units; Chromium and WebKit support it with unitless numbers, consistent [with the usual SVG 2 rules for presentation attributes](https://svgwg.org/svg2-draft/types.html#syntax). Firefox does not support `transform-origin` as a presentation attribute.

Based on the current support, I'd recommend adding a presentation attribute for `transform-origin` to SVG 2.

**Comment by dirkschulze** [comment]
@AmeliaBR It already is: https://www.w3.org/TR/css-transforms-1/#transform-attribute-specificity we should update SVG2's presentation attribute list.

**Comment by AmeliaBR** [comment]
Ah, great. And agreed, we should update the spec to match. & then file browser bugs.

What about `transform-box`?

**Comment by dirkschulze** [comment]
@AmeliaBR `transform-box` is not specified as presentation attribute. Do you see browsers that implemented it as such? Even if not, do you see a need to specify it as presentation attribute? (The other transforms properties are part of level 2 and we have more time to discuss them later.)

**Comment by cdoublev** [comment]
I'm struggling to create a good code demonstration for the following but in a few words it seems a bit strange to me to get unitless values in `transform-origin` converted to absolute values in the user coordinate system (`px`), while a unitless value in `translate()` assigned to the `transform` attribute, stay relative to the svg coordinate system.

Eg. suppose you have a `svg` whose view box is `0 0 1000 1000` and its size in the user space is `500px, 500px`, and you want to rotate a `path` around one of its point located at `200, 200`, you should use `transform-origin: 100 100` (or  `transform-origin: 20% 20%`) instead of `transform-origin: 200 200`.

I'm sorry for this late comment.

**Comment by BigBadaboom** [comment]
@cdoublev I'm not sure how you comment relates to this bug.

Coords in a `transform-origin` would behave the same whether they are in a presentation attribute, or in a CSS rule.  The only real difference would be in the parsing. Presentation attributes have slightly different parsing rules.  For example, they don't need units.

> you want to rotate a path around one of its point located at 200, 200, you should use transform-origin="100 100"

If I understand you correctly, then no.  You would use `transform-origin="200 200"`.

**Comment by cdoublev** [comment]
Sorry, because of a CSS `width` and `height` rule I forgot in my code, I mistakenly believed that unitless values in the `transform-origin` attribute were used as pixel values: the `width` and `height` attributes in my `svg` element were overriden by the corresponding CSS rules. And since I couldn't find in or understand from the specification, such as the section linked in Amelia's first comment, I believed for a moment that it was the expected behavior. [This issue](https://github.com/w3c/svgwg/issues/379) confirms that the meaning of unitless value in attribute is not clearly defined yet.
