### ISSUE TITLE
SVG no longer defines any attributes as required

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/svgwg#710]
The current SVG spec sources don’t normatively define any attributes as required.

For example, at https://github.com/w3c/svgwg/blob/master/master/shapes.html#L63 the sources define the `width` and `height` content attributes for the `rect` element, but no part of the spec normatively defines those attributes as required.

However, if the `width` and `height` content attributes are omitted from a `rect` element, the `rect` element won’t be displayed correctly in Firefox (even if a document attempts to set the width and height using CSS instead).

It seems likely that there are other cases where, if certain attributes are omitted from an element, some UAs won’t display the element as expected.

The original SVG 1.1 spec did normatively define certain attributes as required. I’d guess implementation behavior in some UAs was written with the assumption that those required attributes are present — that the expected display behavior depends on them being present. And I would guess that the SVG 1.1 defined those attributes as required in order to make it clear to author-developers that they needed to include those required attributes in order to get expected behavior.

However, the required attributes were never normatively defined as  required in the actual spec prose. Instead, the SVG 1.1 spec embedded a formalism — a DTD — that normatively defined the requirements. For example, see the section for the `rect` element:

https://www.w3.org/TR/2003/REC-SVG11-20030114/shapes.html#RectElement

…which has a DTD fragment that contains the following:

```
    width %Length.datatype; #REQUIRED
    height %Length.datatype; #REQUIRED
```

But when the Second Edition of the SVG 1.1 spec was  published, those embedded DTD fragments were all dropped. And because the requirements weren’t otherwise normatively stated in the spec prose, the SVG spec lost all its definitions about required attributes.

And the current SVG spec sources just carried over those omissions.

So it seems like the spec sources need to be updated to normatively (re)define the required-attribute cases in the actual spec prose

**Comment by AmeliaBR** [comment]
I don't have any background on whether dropping required elements from SVG 1.1 was intentional or not.

But some points to consider:

- In SVG 1.1 and SVG 2, there are clear rules about what happens if these attributes are missing: the element is not rendered.  Which is also what would happen if the element was in error.  But by _not_ saying that the SVG element is invalid without the attribute, it becomes valid to dynamically set their values from script or using an animation element, causing the element to be rendered at that point.

- In SVG 2, the [geometry attributes](https://svgwg.org/svg2-draft/geometry.html) are not required even for rendering, because you can set their values with CSS instead.  (If you don't set them with CSS either, the initial values of the properties have the same effect of causing the element not to render.)

**Comment by domenic** [comment]
> In SVG 2, the geometry attributes are not required even for rendering, because you can set their values with CSS instead.

I was hoping that was true. I'll note that Firefox doesn't follow this; it will instead follow your first bullet and not render the element. A web platform test and bug on Firefox would be pretty sweet in straightening this out; I was sad to have to repeat `width="10" height="10" class="foo"` everywhere instead of just `class="foo"`. (This was in https://github.com/whatwg/html/commit/1ce97b6b8af575f9846bdedf3ccb5e255040c92d#diff-36cd38f49b9afa08222c0dc9ebfe35ebR88238)

**Comment by AmeliaBR** [comment]
@domenic Firefox recently added support for the geometry properties in v69, give it a few months to reach stable: https://bugzilla.mozilla.org/show_bug.cgi?id=1383650

(But yes, we do need a proper test suite! The Chromium/WebKit implementations are probably buggy, too.)

**Comment by dirkschulze** [comment]
@sideshowbarker Note that the DTD does not apply to SVG2 but SVG1.1 only. Instead we actually use the prose approach and normatively specify the content model of SVG and with it the attributes  of an element. I don't think there is any attribute required to be set on any SVG element to make the SVG document a conform/valid document.

However, there is an IEC group that is interested in formalizing the SVG content model in a machine readable markup language to validate SVGs.

@domenic @AmeliaBR Safari and WebKit did implement Geometry Properties already. Since the spec is in CR, Firefox is free to ship Geometry Properties when ever the team thinks it is ready to ship.

**Comment by ewilligers** [comment]
width and height geometry properties have been [tested](https://github.com/web-platform-tests/wpt/pull/14447) since last year.

**Comment by dirkschulze** [comment]
@sideshowbarker I am going to close the issue. If I missed attributes that indeed are required for a conform SVG file and those were not specified normatively in the spec as required, please open new issues with specific change requests for those attributes.

**Comment by AmeliaBR** [comment]
I've just reviewed the [SVG 1.1 DTD](https://www.w3.org/TR/SVG11/svgdtd.html). For all attributes marked required there, I think SVG 2 either defines a default value or an attribute-not-present behavior. So the absence of the attribute isn't an error.

Which may not be as helpful for creating validator warnings, but supports the case of dynamic DOM.
