### ISSUE TITLE
What properties from a style element or attribute should be applied to an element?

### ISSUE THREAD

**Issue by RazrFalcon** [w3c/svgwg#721]
I guess that only the presentation attributes can be set via CSS/style. So something like this:

```xml
<rect x="20" y="20" width="160" style="height:160" fill="red"/>
```

is invalid. But Chrome renders it anyway.

On the other hand, `transform` isn't a presentation attribute, but everyone will apply it if it set in CSS/style.

Does the spec specifies this somewhere?

**Comment by BigBadaboom** [comment]
`height` is valid. It was added in SVG2. Chrome supports it now.  And it is coming to Firefox in one the next couple of releases.

Information on geometry properties is here:
https://svgwg.org/svg2-draft/single-page.html#chapter-geometry

Each of the spec versions has an appendix listing all the valid stylable properties.
- https://www.w3.org/TR/SVG11/single-page.html#chapter-propidx
- https://svgwg.org/svg2-draft/single-page.html#chapter-propidx

**Comment by RazrFalcon** [comment]
I'm targeting SVG 1.1

Neither `height` or `transform` are set in the SVG 1.1 property index, but everyone still support `transform`. Is there a reason for that?

`transform` indeed a presentation attribute in the SVG 2.

Surprisingly, `width` and `height` are mentioned in the SVG 1.1 spec, in the [6.16 User agent style sheet](https://www.w3.org/TR/SVG11/styling.html#UAStyleSheet). So we should be able to set them via CSS?

PS: looks like Chrome ignores the `version` attribute, so I can't force SVG 1.1. Or it applies `height` even in SVG 1.1

**Comment by BigBadaboom** [comment]
> everyone still support transform. Is there a reason for that?

That's because the CSS Transforms spec came along (just after SVG 1.1 was published) and turned the `transform` attribute into a stylable property.

https://drafts.csswg.org/css-transforms/#svg-transform

If you click through the "Previous versions" links, you can follow the history of changes.

> Surprisingly, width and height are mentioned in the SVG 1.1 spec, in the 6.16 User agent style sheet. So we should be able to set them via CSS?

It's not clear, but that is referring to the "layout" of SVG elements. Meaning in an HTML page.  The `width` and `height` attributes of root SVG elements are stylable in HTML, but that's not the case for `<svg>` elements in general.  Inner `<svg>` elements cannot have their `width` and `height` styled.

Example: https://jsfiddle.net/hgmk94s2/

**Comment by RazrFalcon** [comment]
So for SVG 1.1 `transform` is a valid property, but geometry properties aren't?

**Comment by BigBadaboom** [comment]
Correct.

**Comment by RazrFalcon** [comment]
Thanks.

**Comment by tabatkins** [comment]
> PS: looks like Chrome ignores the version attribute, so I can't force SVG 1.1. Or it applies height even in SVG 1.1

Note that language versions don't exist on the web (and not, in general, in any renderers). The *specs* are leveled for historical documentation; the implementations are "whatever's latest that they've gotten around to implementing".
