### ISSUE TITLE
XSS Security concerns prevent CSS to be used in SVG animated images

### ISSUE THREAD

**Issue by Emasoft** [w3c/svgwg#75]
Because of the announce by the SVGWG to deprecate SMIL in favour of CSS and Web Animations api in SVG2, a big problem arises for content creators and content creation tools developers.   
  
With SMIL you can now safely create an animated SVG icon (like those: http://www.tbyrne.org/viber-animated-svgs ), and embed them in the HTML page using the IMG tag.   

This prevents any XSS attack because scripts are not executed inside the IMG tag, while SMIL works just fine. Adding an animated SVG is currently as easy and safe as posting an animated GIF. 

Because of this concern, security guidelines for SVG animated images or icons reccomends to post them ONLY inside IMG tags, and websites are now increasingly doing it.  
  
But If you remove SMIL in SVG2, the only way to create an animated SVG image that works inside an IMG tag is by using CSS.  
  
Unfortunately, this winds up not being useful in practice because ALL the current ways to use CSS with SVG are plagued by problems that make them UNPRACTICABLE.   
  
Specifically:  
  
1. Embed the CSS in the SVG document
    * Can't use CSS preprocessors (LESS, SASS)
    * Can't target parent elements (button hover, etc.)
    * Makes maintenance difficult
2. Link to a CSS file in your SVG document
    * Sharing styles with your HTML means duplicating paths across your project,
      making maintenance a pain
    * Not sharing styles with your HTML means extra HTTP requests (and likely
      duplicating paths between different SVGs)
    * Still can't target parent elements
    * Your SVG becomes coupled to your external stylesheet, complicating reuse.
3. Embed the SVG in your HTML
    * Bloats your HTML
    * SVGs can't be cached by browsers between pages.
    * A maintenance nightmare
4. Load the SVG with an XHR request and then embed it in the document
    * This places the loaded file into the DOM, so it allows XSS attacks. 
5. Access the SVG elements via the USE tag from an external resource
    * This injects the external SVG element into the DOM, so it allows XSS attacks. 
  
So currently there is no practical way to use CSS for creating SVG Animations. All the current options are unpractical or insecure.   
  
When SMIL will be removed in SVG2 this problem will become blocking for a lot of web sites.
An alternative solution is needed.  
  
NOTE: this issue was first rised by the author of the React-InlineSVG component ( https://github.com/matthewwithanm/react-inlinesvg ).

**Comment by tabatkins** [comment]
"Only embed SVG via `<img>`" is for *untrusted* SVG.  If you trust it, embedding via `<iframe>`, `<object>`, or directly in the HTML is just fine.

As has been stated multiple times, CSS and SMIL offer comparable animation facilities, and in several of the places where CSS lacks a SMIL ability, we plan to add it to the CSS animation model.

Your #1 isn't a CSS vs SMIL issue.  CSS Animations are comparable in authoring/maintenance to SMIL, so any issues are issues with both.

#2 isn't an issue, because you don't need to link in your CSS.  Just inline it.

#3, #4, and #5 aren't relevant to the complaint at hand, which is handling untrusted SVG.  Embedding an untrusted SVG directly into your HTML is obviously a huge nightmare.

I'll remind you again that in today's world SMIL does not work at all for users with IE/Edge, so any animated images are already "broken" for a substantial chunk of one's userbase.
