### ISSUE TITLE
Proposal: rx and ry attributes for radialGradient

### ISSUE THREAD

**Issue by dustdfg** [w3c/svgwg#872]
https://www.w3.org/TR/SVG2/styling.html (spec section?)
https://www.w3.org/TR/SVG2/pservers.html#RadialGradientAttributes (spec section?)

This version of specification defines only one attribute for radius (r) of radialGradient so radialGradient is simple "circle" but sometimes I need an "ellipse". Now I can't create radialGradient in the shape of an ellipse without gradientTransform attribute. I propose replace r attribute by rx and ry similar to rx and ry attributes that uses <ellipse> element. So, I also propose replace attribute for radius of focal circle (fr) with two attributes each one for one axis.

**Comment by Doktorchen** [comment]
You often still need to rotate the main axis.
In general you can use the attribute gradientTransform to get an effect of at least simple distortions of any gradient.

Isn't this option sufficient?

With new attributes you have to define precisely and backward compatible the new behaviour.
There are already bugs in some viewers due to inconsistencies between normative SVG gradients and newer proposals for CSS gradients, expecially concerning the automatic corrections, if the focal point it noted to be outside the radius.

**Comment by dustdfg** [comment]
Hello @Doktorchen 
I think I agree with you. Thank you for your answer.
