### ISSUE TITLE
variable width stroke proposal status

### ISSUE THREAD

**Issue by Offbeatmammal** [w3c/svgwg#953]
I've been trying to 'fake' variable width lines using fill, but found [this proposal](https://www.w3.org/Graphics/SVG/WG/wiki/Proposals/Variable_width_stroke) which would potentially make the job a lot easier (even in it's simplest form of allowing a 'start' and 'end' width and smoothly adjusting along the path).

It appears last time this had any action was in [2013](https://www.w3.org/Graphics/SVG/WG/wiki/F2F/Tokyo_2013/Agenda), so I'm guessing it's not going anywhere, but thought it was worth checking

**Comment by birtles** [comment]
It looks like that was my proposal and from what I can tell it was [discussed at the 2013 Tokyo F2F](https://www.w3.org/2013/06/03-svg-minutes.html#item19). I then [updated the proposal in Septmber](https://lists.w3.org/Archives/Public/www-svg/2013Sep/0029.html). I don't know if it was ever discussed after that. (I notice the polyfill is broken too because we deprecated several SVG path APIs.)

I think since that point browsers have been investing less in new SVG features for various reasons. I believe I might also have received feedback offline that adding primitives not natively supported by underlying graphics libraries would be a significant hurdle for many implementations.

**Comment by Offbeatmammal** [comment]
thanks, I guess with the workaround of manually creating the shape and filling is a solution (and doesn't add complexity, or require extra work from browsers).
