### ISSUE TITLE
Circles and markers

### ISSUE THREAD

**Issue by xgebi** [w3c/svgwg#956]
[Spec](https://svgwg.org/svg2-draft/painting.html#VertexMarkerProperties)

Hi, I've been messing with markers and circles and want to ask if there's an example how they should work together?

When I tried to add any marker attribute to a `circle`, nothing happened. When I tried it with `path` it did.

```HTML
<circle r="50" cy="75" cx="200" class="stroke-behind" marker-start="url(#triangle)" marker-end="url(#triangle)" marker-mid="url(#triangle)"/>
```

I iterated through all three attributes but nothing happened.

When I looked at the spec, it says that it applies to all shapes but all the examples that I was able to find are with paths. Is there a place where I could see how it should work with `circle`?

**Comment by Tavmjong** [comment]
I don't believe the browsers support markers on shapes. Inkscape does.

The start and end markers should be at 3 o'clock, and the mid markers at 12, 6 and 9. The path goes in a clock-wise direction.

The decomposition of a circle into path segments is defined at https://www.w3.org/TR/SVG/shapes.html#CircleElement

You can use a path with four arc segments to mimic the expected behavior.


----- Original Message -----
| From: "Sarah Gebauer" ***@***.***>
| To: "w3c/svgwg" ***@***.***>
| Cc: "Subscribed" ***@***.***>
| Sent: Thursday, October 31, 2024 9:10:39 PM
| Subject: [w3c/svgwg] Cirlces and markers (Issue #956)
| 
| 
| 
| 
| 
| Spec
| 
| Hi, I've been messing with markers and circles and want to ask if
| there's an example how they should work together?
| 
| When I tried to add any marker attribute to a circle , nothing
| happened. When I tried it with path it did.
| < circle r =" 50 " cy =" 75 " cx =" 200 " class =" stroke-behind "
| marker-start =" url(#triangle) " marker-end =" url(#triangle) "
| marker-mid =" url(#triangle) "/>
| 
| I iterated through all three attributes but nothing happened.
| 
| When I looked at the spec, it says that it applies to all shapes but
| all the examples that I was able to find are with paths. Is there a
| place where I could see how it should work with circle ?
| 
| —
| Reply to this email directly, view it on GitHub , or unsubscribe .
| You are receiving this because you are subscribed to this thread.
| Message ID: <w3c/svgwg/issues/956 @ github . com>

**Comment by xgebi** [comment]
Yeah, it looks like I've stumbled into an unmapped forest with this one. I was hoping that I'm doing something wrong.
